var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};
$jscomp.checkStringArgs=function(a,d,e){if(null==a)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,e){a!=Array.prototype&&a!=Object.prototype&&(a[d]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,e,g){if(d){e=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var k=a[g];k in e||(e[k]={});e=e[k]}a=a[a.length-1];g=e[a];d=d(g);d!=g&&null!=d&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,e){var d=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var k=d.length,f=a.length;e=Math.max(0,Math.min(e|0,d.length));for(var h=0;h<f&&e<k;)if(d[e++]!=a[h++])return!1;return h>=f}},"es6","es3");
(function(a){a.SymBfw.notificationCenterProxy=function(a){var d=a.utils.isNil,g=a.utils.isntNil,k=a.logger,f=a.constants.uiConstants.NOTIFICATION,h=a.uiUtils,m=a.utils.isArray,l=a.extensionAdapter,c={timeoutShowNotification:null,getNotificationIframeID:function(){return f.IFRAME_ID+"-"+l.getExtensionId()},closeNotifications:function(){var a=c.getNotificationIframeID();a=document.querySelectorAll("[id='"+a+"']");if(g(a))for(var b=0;b<a.length;b++)document.documentElement.removeChild(a[b])},handleMessage:function(a){switch(a.eventID){case f.MESSAGES.NOTIFICATION_QUEUE_MESSAGE:if(!m(a.notificationArray)){k.log("unexpected payload for NOTIFICATION_QUEUE_MESSAGE");
break}g(c.timeoutShowNotification)&&clearTimeout(c.timeoutShowNotification);c.timeoutShowNotification=setTimeout(function(){c.notificationArray=a.notificationArray;0===c.notificationArray.length?c.closeNotifications():(c.setIsAllowed(c.notificationArray),c.showNotifications(),c.timeoutShowNotification=null)},100);break;case f.MESSAGES.HIDE_NOTIFICATIONS:c.closeNotifications();break;case f.MESSAGES.RESIZE_IFRAME_HEIGHT:var b=c.getNotificationIframeID();b=document.getElementById(b);var d=parseFloat(b.height);
b.height=d+a.iframeHeight;break;case f.MESSAGES.FIXED_IFRAME_HEIGHT:b=c.getNotificationIframeID(),b=document.getElementById(b),b.height=a.iframeHeight}},setIsAllowed:function(a){a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())b=b.value,c.isEmptyList(b.allowListedUrls)&&c.isEmptyList(b.blockListedUrls)?b.isAllowed=!0:c.isEmptyList(b.allowListedUrls)?b.isAllowed=!c.isPageUrlInList(b.blockListedUrls):b.isAllowed=c.isPageUrlInList(b.allowListedUrls)},isPageUrlInList:function(a){return!c.isEmptyList(a)&&
a.some(function(a){return a.startsWith(document.location.origin)})?!0:!1},isEmptyList:function(a){return!m(a)||0===a.length},showNotifications:function(){c.closeNotifications();var a=l.getExtensionURL(f.HTML),b=l.getExtensionURL(f.STYLE);h.injectStyle(b);b=f.IFRAME_ID+"-"+l.getExtensionId();h.createFrame(b,a,f.HEIGHT,f.WIDTH)},addEventListener:function(){l.addContentScriptMessageListener(function(a,b,e){switch(a.id){case f.MESSAGES.DEFAULT_MESSAGE:if(d(a.payload))break;return c.handleMessage(a.payload);
case f.MESSAGES.UI_INIT_PROXY:return b({notifications:c.notificationArray,direction:h.getDirection()})}})},initialize:function(){h.isTopLevelWindow()&&(c.addEventListener(),l.sendMessage({id:f.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:f.MESSAGES.NOTIFICATION_QUEUE_MESSAGE}}))}};window.addEventListener("pageshow",function(a){a.persisted&&c.initialize()});c.initialize();return c}(a.SymBfw)})(window);
