(function(){function k(g,d,b){function c(a,f){if(!d[a]){if(!g[a]){var h="function"==typeof require&&require;if(!f&&h)return h(a,!0);if(m)return m(a,!0);f=Error("Cannot find module '"+a+"'");throw f.code="MODULE_NOT_FOUND",f;}f=d[a]={exports:{}};g[a][0].call(f.exports,function(b){return c(g[a][1][b]||b)},f,f.exports,k,g,d,b)}return d[a].exports}for(var m="function"==typeof require&&require,a=0;a<b.length;a++)c(b[a]);return c}return k})()({1:[function(k,g,d){Object.defineProperty(d,"__esModule",{value:!0});
d.default=function(b){var c=b.strings,d=b.onHandleDecline,a=b.onHandleAccept;b=b.onOpenGlobalPrivacy;return React.createElement("div",{className:"privacy-prompt-container"},React.createElement("div",{className:"privacy-prompt-message-container"},React.createElement("div",null,React.createElement("img",{className:"privacy-prompt-icon",src:"../images/privacy-prompt-logo.svg"})),React.createElement("div",{className:"product-name"},c["Norton Safe Web"]),React.createElement("div",{className:"privacy-prompt-title"},
c["Let us help protect you"]),React.createElement("div",{className:"privacy-prompt-message"},React.createElement("div",{className:"message-without-link"},c["Norton Safe Web must have permission to access and collect the web addresses (urls) that you've visited. This way, we can help detect whether the sites you browse are malicious and help protect you."]),React.createElement("div",{className:"message-with-link"},React.createElement("span",null,c["To better understand our data collection policies, please visit our"]),
React.createElement("button",{onClick:b,className:"button-link link"},c["Global Privacy Statement"],"."))),React.createElement("div",{className:"privacy-prompt-actions"},React.createElement("button",{onClick:a,className:"accept"},c.Accept),React.createElement("button",{onClick:d,className:"decline"},c.Decline))))}},{}],2:[function(k,g,d){(function(b){(function(){function c(a,e){if("function"!==typeof e&&null!==e)throw new TypeError("Super expression must either be null or a function, not "+typeof e);
a.prototype=Object.create(e&&e.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});e&&(Object.setPrototypeOf?Object.setPrototypeOf(a,e):a.__proto__=e)}Object.defineProperty(d,"__esModule",{value:!0});var g=function(){function a(a,b){for(var e=0;e<b.length;e++){var c=b[e];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,c.key,c)}}return function(c,b,d){b&&a(c.prototype,b);d&&a(c,d);return c}}(),a=k("./firstPrivacyPrompt.jsx"),
p=a&&a.__esModule?a:{default:a},f=(a=k("./reviewPrivacyPrompt.jsx"))&&a.__esModule?a:{default:a},h=SymBfw.extensionAdapter,q=SymBfw.utils.isNil,l=NSSS.uiConstants.MESSAGES,n=function(a){function b(a){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");a=(b.__proto__||Object.getPrototypeOf(b)).call(this,a);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=!a||"object"!==typeof a&&"function"!==typeof a?this:a;a.state={firstPrivacyPrompt:!0,
displayPrivacyPrompt:!1};return a}c(b,a);g(b,[{key:"componentDidMount",value:function(){this._checkPrivacyPromptStatus()}},{key:"_checkPrivacyPromptStatus",value:function(){this.setState({displayPrivacyPrompt:!0})}},{key:"_handleDecline",value:function(){this.setState({firstPrivacyPrompt:!1});h.sendMessage({id:l.ON_PRIVACY_CONSENT_DECLINE})}},{key:"_handleAccept",value:function(){this.setState({displayPrivacyPrompt:!1});h.sendMessage({id:l.ON_PRIVACY_CONSENT_ACCEPT})}},{key:"_openGlobalPrivacyStmt",
value:function(){h.sendMessage({id:l.OPEN_GLOBAL_PRIVACY_PAGE})}},{key:"_handleReviewClick",value:function(){this.setState({firstPrivacyPrompt:!0})}},{key:"_handleRemoveNSWClick",value:function(){h.sendMessage({id:l.REMOVE_NSW_CLICKED})}},{key:"render",value:function(){var a=this.state,b=a.firstPrivacyPrompt;return a.displayPrivacyPrompt&&(b?React.createElement(p.default,{strings:this.props.strings,onHandleDecline:this._handleDecline.bind(this),onHandleAccept:this._handleAccept.bind(this),onOpenGlobalPrivacy:this._openGlobalPrivacyStmt.bind(this)}):
React.createElement(f.default,{strings:this.props.strings,onHandleReview:this._handleReviewClick.bind(this),onHandleRemove:this._handleRemoveNSWClick.bind(this)}))}}]);return b}(React.Component);d.default=n;(function(){var a={show:function(){h.sendMessage({id:l.PRIVACY_PROMPT_SCREEN_UI_INIT},function(a){q(a)||ReactDOM.render(React.createElement(n,{direction:a.direction,strings:a.strings}),document.getElementById("container"))})}};b.NSSS.privacyPrompt=a;a.show()})()}).call(this)}).call(this,"undefined"!==
typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{"./firstPrivacyPrompt.jsx":1,"./reviewPrivacyPrompt.jsx":3}],3:[function(k,g,d){Object.defineProperty(d,"__esModule",{value:!0});d.default=function(b){var c=b.strings,d=b.onHandleReview;b=b.onHandleRemove;return React.createElement("div",{className:"privacy-prompt-container"},React.createElement("div",{className:"privacy-prompt-message-container"},React.createElement("div",null,React.createElement("img",{className:"privacy-prompt-icon privacy-prompt-icon-cross",
src:"../images/privacy-prompt-review.svg"})),React.createElement("div",{className:"privacy-prompt-title"},c["Your Permission Is Required"]),React.createElement("div",{className:"privacy-prompt-message"},React.createElement("div",{className:"message-without-link"},c["Norton Safe Web will not work and won't be able to help protect you from malicious websites you might browse."]),React.createElement("div",null,c["Please click below to review your permission and accept our request to collect the anonymous information you submit."])),
React.createElement("div",{className:"privacy-prompt-actions"},React.createElement("button",{onClick:d,className:"review"},c["Review Your Permissions"]),React.createElement("button",{onClick:b,className:"remove"},c["Remove Norton Safe Web"]))))}},{}]},{},[2]);
