/*
 *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
*****************************************************************************/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var a=0;return function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){b!=Array.prototype&&b!=Object.prototype&&(b[a]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(b,a){this.$jscomp$symbol$id_=b;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:a})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function b(c){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+a++,c)}var a=0;return b}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};
$jscomp.makeIterator=function(b){var a="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return a?a.call(b):$jscomp.arrayIterator(b)};$jscomp.arrayFromIterator=function(b){for(var a,c=[];!(a=b.next()).done;)c.push(a.value);return c};$jscomp.arrayFromIterable=function(b){return b instanceof Array?b:$jscomp.arrayFromIterator($jscomp.makeIterator(b))};$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(b){var a=function(){};a.prototype=b;return new a};
$jscomp.underscoreProtoCanBeSet=function(){var b={a:!0},a={};try{return a.__proto__=b,a.a}catch(c){}return!1};$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(b,a){b.__proto__=a;if(b.__proto__!==a)throw new TypeError(b+" is not extensible");return b}:null;
$jscomp.inherits=function(b,a){b.prototype=$jscomp.objectCreate(a.prototype);b.prototype.constructor=b;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(b,a)}else for(c in a)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(a,c);d&&Object.defineProperty(b,c,d)}else b[c]=a[c];b.superClass_=a.prototype};
$jscomp.polyfill=function(b,a,c,d){if(a){c=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];e in c||(c[e]={});c=c[e]}b=b[b.length-1];d=c[b];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function a(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;a.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;a.prototype.asyncExecuteFunction=function(a){d(a,0)};a.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(t){this.asyncThrow_(t)}}}this.batch_=null};a.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(q){b.reject(q)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(q){this.reject_(q);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)g.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var g=new a;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(t){c.reject(t)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(A){g(A)}}:b}var d,g,n=new e(function(a,b){d=a;g=b});this.callWhenSettled_(c(a,d),c(b,g));return n};
e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(c)};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,d){for(var e=$jscomp.makeIterator(a),g=e.next();!g.done;g=e.next())c(g.value).callWhenSettled_(b,
d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function g(b){return function(c){n[b]=c;q--;0==q&&a(n)}}var n=[],q=0;do n.push(void 0),q++,c(d.value).callWhenSettled_(g(n.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(b){if(!(b instanceof Object))throw new TypeError("Iterator result "+b+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(b){this.yieldResult=b};$jscomp.generator.Context.prototype.throw_=function(b){this.abruptCompletion_={exception:b,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(b){this.abruptCompletion_={return:b};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(b){this.abruptCompletion_={jumpTo:b};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(b,a){this.nextAddress=a;return{value:b}};$jscomp.generator.Context.prototype.yieldAll=function(b,a){b=$jscomp.makeIterator(b);var c=b.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=a;else return this.yieldAllIterator_=b,this.yield(c.value,a)};
$jscomp.generator.Context.prototype.jumpTo=function(b){this.nextAddress=b};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(b,a){this.catchAddress_=b;void 0!=a&&(this.finallyAddress_=a)};$jscomp.generator.Context.prototype.setFinallyBlock=function(b){this.catchAddress_=0;this.finallyAddress_=b||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(b,a){this.nextAddress=b;this.catchAddress_=a||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(b){this.catchAddress_=b||0;b=this.abruptCompletion_.exception;this.abruptCompletion_=null;return b};$jscomp.generator.Context.prototype.enterFinallyBlock=function(b,a,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=b||0;this.finallyAddress_=a||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(b,a){a=this.finallyContexts_.splice(a||0)[0];if(a=this.abruptCompletion_=this.abruptCompletion_||a){if(a.isException)return this.jumpToErrorHandler_();void 0!=a.jumpTo&&this.finallyAddress_<a.jumpTo?(this.nextAddress=a.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=b};$jscomp.generator.Context.prototype.forIn=function(b){return new $jscomp.generator.Context.PropertyIterator(b)};
$jscomp.generator.Context.PropertyIterator=function(b){this.object_=b;this.properties_=[];for(var a in b)this.properties_.push(a);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var b=this.properties_.pop();if(b in this.object_)return b}return null};$jscomp.generator.Engine_=function(b){this.context_=new $jscomp.generator.Context;this.program_=b};
$jscomp.generator.Engine_.prototype.next_=function(b){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,b,this.context_.next_);this.context_.next_(b);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(b){this.context_.start_();var a=this.context_.yieldAllIterator_;if(a)return this.yieldAllStep_("return"in a?a["return"]:function(a){return{value:a,done:!0}},b,this.context_.return);this.context_.return(b);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(b){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],b,this.context_.next_);this.context_.throw_(b);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(b,a,c){try{var d=b.call(this.context_.yieldAllIterator_,a);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var b=this.program_(this.context_);if(b)return this.context_.stop_(),{value:b.value,done:!1}}catch(a){this.context_.yieldResult=void 0,this.context_.throw_(a)}this.context_.stop_();if(this.context_.abruptCompletion_){b=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(b.isException)throw b.exception;return{value:b.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(b){this.next=function(a){return b.next_(a)};this.throw=function(a){return b.throw_(a)};this.return=function(a){return b.return_(a)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(b,a){a=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(a,b.prototype);return a};
$jscomp.asyncExecutePromiseGenerator=function(b){function a(a){return b.next(a)}function c(a){return b.throw(a)}return new Promise(function(d,e){function g(b){b.done?d(b.value):Promise.resolve(b.value).then(a,c).then(g,e)}g(b.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(b){return $jscomp.asyncExecutePromiseGenerator(b())};$jscomp.asyncExecutePromiseGeneratorProgram=function(b){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b)))};
$jscomp.owns=function(b,a){return Object.prototype.hasOwnProperty.call(b,a)};$jscomp.assign="function"==typeof Object.assign?Object.assign:function(b,a){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)$jscomp.owns(d,e)&&(b[e]=d[e])}return b};$jscomp.polyfill("Object.assign",function(b){return b||$jscomp.assign},"es6","es3");$jscomp.polyfill("Object.setPrototypeOf",function(b){return b||$jscomp.setPrototypeOf},"es6","es5");
$jscomp.iteratorFromArray=function(b,a){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var c=0,d={next:function(){if(c<b.length){var e=c++;return{value:a(e,b[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.polyfill("Object.entries",function(b){return b?b:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push([d,a[d]]);return b}},"es8","es3");$jscomp.polyfill("Object.values",function(b){return b?b:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push(a[d]);return b}},"es8","es3");$jscomp.polyfill("Object.is",function(b){return b?b:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(a,b){var c=this;c instanceof String&&(c=String(c));var e=c.length;b=b||0;for(0>b&&(b=Math.max(b+e,0));b<e;b++){var g=c[b];if(g===a||Object.is(g,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(b,a,c){if(null==b)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return b+""};$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
!function(b,a){"object"==typeof exports&&"object"==typeof module?module.exports=a():"function"==typeof define&&define.amd?define([],a):"object"==typeof exports?exports.HeartbeatSDK=a():b.HeartbeatSDK=a()}(window,function(){return function(b){function a(d){if(c[d])return c[d].exports;var e=c[d]={i:d,l:!1,exports:{}};return b[d].call(e.exports,e,e.exports,a),e.l=!0,e.exports}var c={};return a.m=b,a.c=c,a.d=function(b,c,g){a.o(b,c)||Object.defineProperty(b,c,{enumerable:!0,get:g})},a.r=function(a){$jscomp.initSymbol();
$jscomp.initSymbol();$jscomp.initSymbol();"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})},a.t=function(b,c){if((1&c&&(b=a(b)),8&c)||4&c&&"object"==typeof b&&b&&b.__esModule)return b;var d=Object.create(null);if(a.r(d),Object.defineProperty(d,"default",{enumerable:!0,value:b}),2&c&&"string"!=typeof b)for(var e in b)a.d(d,e,function(a){return b[a]}.bind(null,e));return d},a.n=function(b){var c=
b&&b.__esModule?function(){return b.default}:function(){return b};return a.d(c,"a",c),c},a.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},a.p="",a(a.s=0)}({"./node_modules/@nll/telemetry/dist/base/base.js":function(b,a,c){function d(){var a=g.getGlobalObject();return a.__NORTONLIFELOCK__=a.__NORTONLIFELOCK__||{base:void 0},a}function e(a){return a&&a.__NORTONLIFELOCK__&&a.__NORTONLIFELOCK__.base?a.__NORTONLIFELOCK__.base:(a.__NORTONLIFELOCK__=a.__NORTONLIFELOCK__||{},a.__NORTONLIFELOCK__.base=
new u,a.__NORTONLIFELOCK__.base)}Object.defineProperty(a,"__esModule",{value:!0});var g=c("./node_modules/@nll/utils/esm/index.js"),n=c("./node_modules/@nll/telemetry/dist/base/noopclient.js"),u=function(a){this._client=a||new n.NoopClient};u.prototype.bindClient=function(a){this._client=a};u.prototype.getClient=function(){return this._client};a.Base=u;a.getMainContainer=d;a.getBaesFromContainer=e;a.getInstance=function(){return e(d())}},"./node_modules/@nll/telemetry/dist/base/index.js":function(b,
a,c){Object.defineProperty(a,"__esModule",{value:!0});b=c("./node_modules/@nll/telemetry/dist/base/base.js");a.getInstance=b.getInstance;a.Base=b.Base},"./node_modules/@nll/telemetry/dist/base/noopclient.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/types/esm/index.js"),e=c("./node_modules/@nll/utils/esm/index.js");a.NoopClient=function(){};a.NoopClient.prototype.ping=function(a){return e.SyncPromise.resolve({reason:"noop: ping has been skipped.",
status:d.Status.Skipped})};a.NoopClient.prototype.flush=function(a){return e.SyncPromise.resolve(!1)};a.NoopClient.prototype.defaults=function(a){};a.NoopClient.prototype.getOptions=function(){return{}};a.NoopClient.prototype.setMid=function(a){};a.NoopClient.prototype.getMid=function(){return""}},"./node_modules/@nll/telemetry/dist/browser/backend.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/telemetry/dist/core/index.js"),e=c("./node_modules/@nll/utils/esm/index.js"),
g=c("./node_modules/@nll/telemetry/dist/browser/transports/index.js");a.BrowserBackend=function(){return d.BaseBackend.apply(this,arguments)||this};$jscomp.inherits(a.BrowserBackend,d.BaseBackend);a.BrowserBackend.prototype._setupTransport=function(){if(!this._options.url)return d.BaseBackend.prototype._setupTransport.call(this);var a=Object.assign(Object.assign({},this._options.transportOptions),{url:this._options.url});return this._options.transport?new this._options.transport(a):e.supportsBeacon()?
new g.BeaconTransport(a):e.supportsFetch()?new g.FetchTransport(a):new g.XHRTransport(a)}},"./node_modules/@nll/telemetry/dist/browser/client.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/telemetry/dist/core/index.js"),e=c("./node_modules/@nll/telemetry/dist/browser/backend.js");a.BrowserClient=function(a){return d.BaseClient.call(this,e.BrowserBackend,a)||this};$jscomp.inherits(a.BrowserClient,d.BaseClient)},"./node_modules/@nll/telemetry/dist/browser/index.js":function(b,
a,c){Object.defineProperty(a,"__esModule",{value:!0});b=c("./node_modules/tslib/tslib.es6.js");var d=c("./node_modules/@nll/telemetry/dist/browser/client.js");a.BrowserClient=d.BrowserClient;d=c("./node_modules/@nll/telemetry/dist/browser/sdk.js");a.init=d.init;a.ping=d.ping;a.flush=d.flush;a.defaults=d.defaults;a.setMid=d.setMid;a.getOptions=d.getOptions;d=c("./node_modules/@nll/telemetry/dist/browser/backend.js");a.BrowserBackend=d.BrowserBackend;b.__exportStar(c("./node_modules/@nll/telemetry/dist/browser/transports/index.js"),
a)},"./node_modules/@nll/telemetry/dist/browser/sdk.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/telemetry/dist/core/index.js"),e=c("./node_modules/@nll/telemetry/dist/browser/client.js"),g=c("./node_modules/@nll/telemetry/dist/base/index.js");a.init=function(a){d.initAndBind(e.BrowserClient,Object.assign({product:"Norton",version:"1.0.0",url:"https://stats.norton.com/n/p",enabled:!1},a))};a.ping=function(a){return g.getInstance().getClient().ping(a)};
a.flush=function(){return g.getInstance().getClient().flush()};a.defaults=function(a){g.getInstance().getClient().defaults(a)};a.setMid=function(a){g.getInstance().getClient().setMid(a)};a.getOptions=function(){return g.getInstance().getClient().getOptions()}},"./node_modules/@nll/telemetry/dist/browser/transports/base.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/utils/esm/index.js");a.BaseTransport=function(a){this.options=a;this._buffer=new d.PromiseBuffer(30);
this.url=a.url};a.BaseTransport.prototype.sendPing=function(a){throw new d.NortonError("Transport Class has to implement `sendEvent` method");};a.BaseTransport.prototype.close=function(a){return this._buffer.drain(a)}},"./node_modules/@nll/telemetry/dist/browser/transports/beacon.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/types/esm/index.js"),e=c("./node_modules/@nll/telemetry/dist/browser/transports/base.js"),g=c("./node_modules/@nll/utils/esm/index.js"),
n=c("./node_modules/@nll/utils/esm/index.js");a.BeaconTransport=function(){return e.BaseTransport.apply(this,arguments)||this};$jscomp.inherits(a.BeaconTransport,e.BaseTransport);a.BeaconTransport.prototype.sendPing=function(a){var b=new URL(this.url+"?"+g.urlEncode(a));return this._buffer.add(new n.SyncPromise(function(a,c){navigator.sendBeacon(b.toString())?a({status:d.Status.Success}):c({status:d.Status.Failed})}))}},"./node_modules/@nll/telemetry/dist/browser/transports/fetch.js":function(b,a,
c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/types/esm/index.js"),e=c("./node_modules/@nll/utils/esm/index.js"),g=c("./node_modules/@nll/telemetry/dist/browser/transports/base.js"),n=c("./node_modules/@nll/utils/esm/index.js");a.FetchTransport=function(){return g.BaseTransport.apply(this,arguments)||this};$jscomp.inherits(a.FetchTransport,g.BaseTransport);a.FetchTransport.prototype.sendPing=function(a){var b={method:"POST",credentials:"omit",referrerPolicy:e.supportsReferrerPolicy()?
"origin":""};a=new URL(this.url+"?"+n.urlEncode(a));var c=e.getGlobalObject();return this._buffer.add(c.fetch(a.toString(),b).then(function(a){return{status:d.Status.fromHttpCode(a.status),response:a}}).catch(function(a){return{status:d.Status.Failed}}))}},"./node_modules/@nll/telemetry/dist/browser/transports/index.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});b=c("./node_modules/@nll/telemetry/dist/browser/transports/base.js");a.BaseTransport=b.BaseTransport;b=c("./node_modules/@nll/telemetry/dist/browser/transports/fetch.js");
a.FetchTransport=b.FetchTransport;b=c("./node_modules/@nll/telemetry/dist/browser/transports/xhr.js");a.XHRTransport=b.XHRTransport;c=c("./node_modules/@nll/telemetry/dist/browser/transports/beacon.js");a.BeaconTransport=c.BeaconTransport},"./node_modules/@nll/telemetry/dist/browser/transports/xhr.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/types/esm/index.js"),e=c("./node_modules/@nll/utils/esm/index.js"),g=c("./node_modules/@nll/telemetry/dist/browser/transports/base.js"),
n=c("./node_modules/@nll/utils/esm/index.js");a.XHRTransport=function(){return g.BaseTransport.apply(this,arguments)||this};$jscomp.inherits(a.XHRTransport,g.BaseTransport);a.XHRTransport.prototype.sendPing=function(a){var b=this;return this._buffer.add(new e.SyncPromise(function(c,e){var g=new XMLHttpRequest;g.onreadystatechange=function(){4===g.readyState&&(200!==g.status?e(g):c({status:d.Status.fromHttpCode(g.status)}))};var l=new URL(b.url+"?"+n.urlEncode(a));g.open("POST",l.toString());g.send()}))}},
"./node_modules/@nll/telemetry/dist/core/basebackend.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/telemetry/dist/core/transports/index.js");a.BaseBackend=function(a){this._options=a;this._transport=this._setupTransport()};a.BaseBackend.prototype._setupTransport=function(){return new d.NoopTransport};a.BaseBackend.prototype.sendPing=function(a){return this._transport.sendPing(a)};a.BaseBackend.prototype.getTransport=function(){return this._transport}},
"./node_modules/@nll/telemetry/dist/core/baseclient.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/types/esm/index.js"),e=c("./node_modules/@nll/utils/esm/index.js");a.BaseClient=function(a,b){this._backend=new a(b);this._options=b;this._mid="00000000000000000000000000000000";this._defaults={error:0}};a.BaseClient.prototype.ping=function(a){var b=this._options,c=b.product;b=b.version;c={os:e.getOsInfo().os,mid:this._mid,product:c,version:b,language:navigator.language,
zzz:e.getPingTimestamp()};return this.isEnabled()?this._backend.sendPing(Object.assign(Object.assign(Object.assign({},this._defaults),a),c)):Promise.resolve({status:d.Status.Skipped})};a.BaseClient.prototype.flush=function(a){return this.getBackend().getTransport().close(a).then(function(a){return a})};a.BaseClient.prototype.defaults=function(a){this._defaults=Object.assign({},a)};a.BaseClient.prototype.setMid=function(a){this._mid=a};a.BaseClient.prototype.getMid=function(){return this._mid};a.BaseClient.prototype.getOptions=
function(){return this._options};a.BaseClient.prototype.getBackend=function(){return this._backend};a.BaseClient.prototype.isEnabled=function(){return!1!==this.getOptions().enabled}},"./node_modules/@nll/telemetry/dist/core/index.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});b=c("./node_modules/@nll/telemetry/dist/core/baseclient.js");a.BaseClient=b.BaseClient;b=c("./node_modules/@nll/telemetry/dist/core/sdk.js");a.initAndBind=b.initAndBind;c=c("./node_modules/@nll/telemetry/dist/core/basebackend.js");
a.BaseBackend=c.BaseBackend},"./node_modules/@nll/telemetry/dist/core/sdk.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/telemetry/dist/base/index.js");a.initAndBind=function(a,b){d.getInstance().bindClient(new a(b))}},"./node_modules/@nll/telemetry/dist/core/transports/index.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});c("./node_modules/tslib/tslib.es6.js").__exportStar(c("./node_modules/@nll/telemetry/dist/core/transports/noop.js"),
a)},"./node_modules/@nll/telemetry/dist/core/transports/noop.js":function(b,a,c){Object.defineProperty(a,"__esModule",{value:!0});var d=c("./node_modules/@nll/types/esm/index.js"),e=c("./node_modules/@nll/utils/esm/index.js");a.NoopTransport=function(){};a.NoopTransport.prototype.sendPing=function(a){return e.SyncPromise.resolve({reason:"noop: ping has been skipped.",status:d.Status.Skipped})};a.NoopTransport.prototype.close=function(a){return e.SyncPromise.resolve(!0)}},"./node_modules/@nll/telemetry/dist/index.js":function(b,
a,c){Object.defineProperty(a,"__esModule",{value:!0});c("./node_modules/tslib/tslib.es6.js").__exportStar(c("./node_modules/@nll/telemetry/dist/browser/index.js"),a)},"./node_modules/@nll/types/esm/index.js":function(b,a,c){c.r(a);var d=c("./node_modules/@nll/types/esm/status.js");c.d(a,"Status",function(){return d.a});c.d(a,"TRUE",function(){return 1})},"./node_modules/@nll/types/esm/status.js":function(b,a,c){var d;c.d(a,"a",function(){return d});(function(a){a.Unknown="unknown";a.Skipped="skipped";
a.Success="success";a.RateLimit="rate_limit";a.Invalid="invalid";a.Failed="failed"})(d||(d={}));(function(a){a.fromHttpCode=function(b){return 200<=b&&300>b?a.Success:429===b?a.RateLimit:400<=b&&500>b?a.Invalid:500<=b?a.Failed:a.Unknown}})(d||(d={}))},"./node_modules/@nll/utils/esm/index.js":function(b,a,c){function d(a){switch(Object.prototype.toString.call(a)){case "[object Error]":case "[object Exception]":case "[object DOMException]":return!0;default:return a instanceof Error}}function e(a){return"[object ErrorEvent]"===
Object.prototype.toString.call(a)}function g(a){return"[object DOMError]"===Object.prototype.toString.call(a)}function n(a){return"[object DOMException]"===Object.prototype.toString.call(a)}function u(a){return"[object String]"===Object.prototype.toString.call(a)}function q(a){return null===a||"object"!=typeof a&&"function"!=typeof a}function t(a){return"[object Object]"===Object.prototype.toString.call(a)}function v(a){return"undefined"!=typeof Event&&a instanceof Event}function w(a){return"undefined"!=
typeof Element&&a instanceof Element}function l(a){return"[object RegExp]"===Object.prototype.toString.call(a)}function r(a){return!(!a||!a.then||"function"!=typeof a.then)}function y(a){return t(a)&&"nativeEvent"in a&&"preventDefault"in a&&"stopPropagation"in a}function A(a,b){return new Promise(function(c,f){var H=window.setTimeout(function(){f(Error("timeout"))},a);b.then(function(a){clearTimeout(H);c(a)},function(a){clearTimeout(H);f(a)})})}function O(a,b,c){void 0===c&&(c=3E5);a=fetch(a,b);return Promise.race([a,
A(c,a)])}function D(a,b){return O(a,{signal:b},1E4).then(function(a){return a.ok?a:Promise.reject(a.statusText)}).then(function(a){return a.blob()}).then(function(a){return new Promise(function(b,c){var f=new FileReader;f.onloadend=function(){return b(f.result)};f.onerror=c;f.readAsDataURL(a)})})}function J(a){var b,c=a.split(",");a=null===(b=c[0].match(/:(.*?);/))||void 0===b?void 0:b.shift();b=atob(c[1]);c=b.length;for(var f=new Uint8Array(c);c--;)f[c]=b.charCodeAt(c);return new Blob([f],{type:a})}
function B(a,b){void 0===b&&(b=16);for(var c=-1,f=0,H=a.length;f<H;f++)c=c>>>8^Q[255&(c^a.charCodeAt(f))];return("00000000"+((-1^c)>>>0).toString(b)).substr(-8)}function K(){return"_"+Math.random().toString(36).substr(2,9)}function R(a){return a.reduce(function(a,b){var c,f=Object(S.__read)(b,2);b=f[0];f=f[1];return Object(S.__assign)(Object(S.__assign)({},a),((c={})[b]=f,c))},{})}function C(a){return 0===Object.keys(a).length&&a.constructor===Object}function h(a){return void 0!==a&&("object"!=typeof a||
!a)}function m(){var a="0x0";screen.width&&(a+=(screen.width?screen.width:"")+" x "+(screen.height?screen.height:""));var b,c,f,d=navigator.appVersion,k=navigator.userAgent,e=navigator.appName,h=""+parseFloat(navigator.appVersion);parseInt(navigator.appVersion,10);-1!=(c=k.indexOf("Opera"))&&(e="Opera",h=k.substring(c+6),-1!=(c=k.indexOf("Version"))&&(h=k.substring(c+8)));-1!=(c=k.indexOf("OPR"))?(e="Opera",h=k.substring(c+4)):-1!=(c=k.indexOf("Edge"))?(e="Microsoft Edge",h=k.substring(c+5)):-1!=
(c=k.indexOf("MSIE"))?(e="Microsoft Internet Explorer",h=k.substring(c+5)):-1!=(c=k.indexOf("Chrome"))?(e="Chrome",h=k.substring(c+7)):-1!=(c=k.indexOf("Safari"))?(e="Safari",h=k.substring(c+7),-1!=(c=k.indexOf("Version"))&&(h=k.substring(c+8))):-1!=(c=k.indexOf("Firefox"))?(e="Firefox",h=k.substring(c+8)):-1!=k.indexOf("Trident/")?(e="Microsoft Internet Explorer",h=k.substring(k.indexOf("rv:")+3)):(b=k.lastIndexOf(" ")+1)<(c=k.lastIndexOf("/"))&&(e=k.substring(b,c),h=k.substring(c+1),e.toLowerCase()==
e.toUpperCase()&&(e=navigator.appName));-1!=(f=h.indexOf(";"))&&(h=h.substring(0,f));-1!=(f=h.indexOf(" "))&&(h=h.substring(0,f));-1!=(f=h.indexOf(")"))&&(h=h.substring(0,f));b=parseInt(""+h,10);isNaN(b)&&(h=""+parseFloat(navigator.appVersion),b=parseInt(navigator.appVersion,10));c=/Mobile|mini|Fennec|Android|iP(ad|od|hone)/.test(d);f=!!navigator.cookieEnabled;void 0!==navigator.cookieEnabled||f||(document.cookie="testcookie",f=-1!=document.cookie.indexOf("testcookie"));var Q="unknown",p=[{s:"Windows 10",
r:/(Windows 10.0|Windows NT 10.0)/},{s:"Windows 8.1",r:/(Windows 8.1|Windows NT 6.3)/},{s:"Windows 8",r:/(Windows 8|Windows NT 6.2)/},{s:"Windows 7",r:/(Windows 7|Windows NT 6.1)/},{s:"Windows Vista",r:/Windows NT 6.0/},{s:"Windows Server 2003",r:/Windows NT 5.2/},{s:"Windows XP",r:/(Windows NT 5.1|Windows XP)/},{s:"Windows 2000",r:/(Windows NT 5.0|Windows 2000)/},{s:"Windows ME",r:/(Win 9x 4.90|Windows ME)/},{s:"Windows 98",r:/(Windows 98|Win98)/},{s:"Windows 95",r:/(Windows 95|Win95|Windows_95)/},
{s:"Windows NT 4.0",r:/(Windows NT 4.0|WinNT4.0|WinNT|Windows NT)/},{s:"Windows CE",r:/Windows CE/},{s:"Windows 3.11",r:/Win16/},{s:"Android",r:/Android/},{s:"Open BSD",r:/OpenBSD/},{s:"Sun OS",r:/SunOS/},{s:"Chrome OS",r:/CrOS/},{s:"Linux",r:/(Linux|X11(?!.*CrOS))/},{s:"iOS",r:/(iPhone|iPad|iPod)/},{s:"Mac OS X",r:/Mac OS X/},{s:"Mac OS",r:/(MacPPC|MacIntel|Mac_PowerPC|Macintosh)/},{s:"QNX",r:/QNX/},{s:"UNIX",r:/UNIX/},{s:"BeOS",r:/BeOS/},{s:"OS/2",r:/OS\/2/},{s:"Search Bot",r:/(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves\/Teoma|ia_archiver)/}];
for(m in p){var z=p[m];if(z.r.test(k)){Q=z.s;break}}var m="";p=null;switch(/Windows/.test(Q)&&(p=/Windows (.*)/.exec(k))&&(m=p[1]),Q){case "Mac OS X":(p=/Mac OS X (10[._\d]+)/.exec(k))&&(m=p[1]);break;case "Android":(p=/Android ([._\d]+)/.exec(k))&&(m=p[1]);break;case "iOS":(p=/OS (\d+)_(\d+)_?(\d+)?/.exec(d))&&(m=p[1]+"."+p[2]+"."+(p[3]?p[3]:"0"));break;default:m="0.0.0.0"}return{screen:a,browser:e,browserVersion:h,browserMajorVersion:b,mobile:c,os:Q,osVersion:m,cookies:f}}function z(a){var b=(""+
a).replace(/\D/g,""),c=b.match(/^([1])(\d{3})(\d{3})(\d{4})$/);return c?c[1]+"-"+c[2]+"-"+c[3]+"-"+c[4]:(c=b.match(/^(\d{3})(\d{3})(\d{4})$/))?c[1]+"-"+c[2]+"-"+c[3]:a}function Z(a){return a.toUpperCase().split("").map(function(a){return-1<"ABC".indexOf(a)?2:-1<"DEF".indexOf(a)?3:-1<"GHI".indexOf(a)?4:-1<"JKL".indexOf(a)?5:-1<"MNO".indexOf(a)?6:-1<"PQRS".indexOf(a)?7:-1<"TUV".indexOf(a)?8:-1<"WXYZ".indexOf(a)?9:a}).join("")}function T(){try{return new ErrorEvent(""),!0}catch(H){return!1}}function P(){try{return new DOMError,
!0}catch(H){return!1}}function L(){try{return new DOMException(""),!0}catch(H){return!1}}function I(){if(!("fetch"in Object(x.c)()))return!1;try{return new Headers,new Request(""),new Response,!0}catch(H){return!1}}function ba(){return"sendBeacon"in Object(x.c)().navigator}function ca(){if(!I())return!1;var a=Object(x.c)(),b=null,c=a.document;if(c){var f=c.createElement("iframe");f.hidden=!0;try{c.head.appendChild(f),f.contentWindow&&f.contentWindow.fetch&&(b=-1!==f.contentWindow.fetch.toString().indexOf("native")),
c.head.removeChild(f)}catch(ja){ha.warn("Could not create sandbox iframe for pure fetch check, bailing to window.fetch: ",ja)}}return null===b&&(b=-1!==a.fetch.toString().indexOf("native")),b}function G(){return"ReportingObserver"in Object(x.c)()}function U(){if(!I())return!1;try{return new Request("_",{referrerPolicy:"origin"}),!0}catch(H){return!1}}function V(){var a=Object(x.c)(),b=a.chrome;a="history"in a&&!!a.history.pushState&&!!a.history.replaceState;return!(b&&b.app&&b.app.runtime)&&a}function da(){var a=
("00000000"+Date.now().toString(16)).substr(-8),b=B(a).split("");a=a.split("");var c="0";return[b,b,b,a,a,a,b,b,a,a,b,b,a,a,a,b].forEach(function(a){c+=a.shift()}),c}function W(a){return Object.keys(a).map(function(b){return encodeURIComponent(b)+"="+encodeURIComponent(a[b])}).join("&")}function X(a){return!!a&&!!a.match(X.regex)}function ea(){var a=Object(x.c)().crypto;if(void 0!==a&&a.getRandomValues){var b=new Uint16Array(8);a.getRandomValues(b);b[3]=4095&b[3]|16384;b[4]=16383&b[4]|32768;a=function(a){for(a=
a.toString(16);4>a.length;)a="0"+a;return a};return p(a(b[0])+a(b[1])+a(b[2])+a(b[3])+a(b[4])+a(b[5])+a(b[6])+a(b[7]))}return p("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx".replace(/[x]/g,function(a){var b=16*Math.random()|0;return("x"===a?b:3&b|8).toString(16)}))}function fa(){var a=Object(x.c)().crypto;if(void 0!==a&&a.getRandomValues){var b=new Uint16Array(8);a.getRandomValues(b);b[3]=4095&b[3]|16384;b[4]=16383&b[4]|32768;a=function(a){for(a=a.toString(16);4>a.length;)a="0"+a;return a};return p(a(b[0])+
a(b[1])+a(b[2])+a(b[3])+a(b[4])+a(b[5])+a(b[6])+a(b[7]))}return p("xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"===a?b:3&b|8).toString(16)}))}c.r(a);var S=c("./node_modules/tslib/tslib.es6.js"),E=Object.setPrototypeOf||({__proto__:[]}instanceof Array?function(a,b){return a.__proto__=b,a}:function(a,b){for(var c in b)a.hasOwnProperty(c)||(a[c]=b[c]);return a}),F,Y=function(a){function b(b){var c=this.constructor,f=a.call(this,b)||this;return f.message=
b,f.name=c.prototype.constructor.name,E(f,c.prototype),f}return Object(S.__extends)(b,a),b}(Error);!function(a){a.PENDING="PENDING";a.RESOLVED="RESOLVED";a.REJECTED="REJECTED"}(F||(F={}));var M=function(){function a(a){var b=this;this._state=F.PENDING;this._handlers=[];this._resolve=function(a){b._setResult(F.RESOLVED,a)};this._reject=function(a){b._setResult(F.REJECTED,a)};this._setResult=function(a,c){b._state===F.PENDING&&(r(c)?c.then(b._resolve,b._reject):(b._state=a,b._value=c,b._executeHandlers()))};
this._attachHandler=function(a){b._handlers=b._handlers.concat(a);b._executeHandlers()};this._executeHandlers=function(){b._state!==F.PENDING&&(b._state===F.REJECTED?b._handlers.forEach(function(a){a.onrejected&&a.onrejected(b._value)}):b._handlers.forEach(function(a){a.onfulfilled&&a.onfulfilled(b._value)}),b._handlers=[])};try{a(this._resolve,this._reject)}catch(ia){this._reject(ia)}}return a.prototype.toString=function(){return"[object SyncPromise]"},a.resolve=function(b){return new a(function(a){a(b)})},
a.reject=function(b){return new a(function(a,c){c(b)})},a.all=function(b){return new a(function(c,f){if(Array.isArray(b))if(0!==b.length){var k=b.length,d=[];b.forEach(function(b,h){a.resolve(b).then(function(a){d[h]=a;0===--k&&c(d)}).then(null,f)})}else c([]);else f(new TypeError("Promise.all requires an array as input."))})},a.prototype.then=function(b,c){var f=this;return new a(function(a,k){f._attachHandler({onfulfilled:function(c){if(b)try{return void a(b(c))}catch(aa){return void k(aa)}else a(c)},
onrejected:function(b){if(c)try{return void a(c(b))}catch(aa){return void k(aa)}else k(b)}})})},a.prototype.catch=function(a){return this.then(function(a){return a},a)},a.prototype.finally=function(b){var c=this;return new a(function(a,f){var k,d;return c.then(function(a){d=!1;k=a;b&&b()},function(a){d=!0;k=a;b&&b()}).then(function(){d?f(k):a(k)})})},a}(),f=function(){function a(a){this._limit=a;this._buffer=[]}return a.prototype.isReady=function(){return void 0===this._limit||this.length()<this._limit},
a.prototype.add=function(a){var b=this;return this.isReady()?(-1===this._buffer.indexOf(a)&&this._buffer.push(a),a.then(function(){return b.remove(a)}).then(null,function(){return b.remove(a).then(null,function(){})}),a):M.reject(new Y("Not adding Promise due to buffer limit reached."))},a.prototype.remove=function(a){return this._buffer.splice(this._buffer.indexOf(a),1)[0]},a.prototype.length=function(){return this._buffer.length},a.prototype.drain=function(a){var b=this;return new M(function(c){var f=
setTimeout(function(){a&&0<a&&c(!1)},a);M.all(b._buffer).then(function(){clearTimeout(f);c(!0)}).then(null,function(){c(!0)})})},a}(),k={dark:"color: #222",purple:"color: #9966ff",symantec:"color: #fdbb30",blueBg:"background: #A9CCE3;",greenBg:"background: #58D68D;",red:"color: #E74C3C",yellow:"color: #F7DC6F",error:"background: #E74C3C;",orangeBg:"background: #F39C12;"},Q=[0,1996959894,3993919788,2567524794,124634137,1886057615,3915621685,2657392035,249268274,2044508324,3772115230,2547177864,162941995,
2125561021,3887607047,2428444049,498536548,1789927666,4089016648,2227061214,450548861,1843258603,4107580753,2211677639,325883990,1684777152,4251122042,2321926636,335633487,1661365465,4195302755,2366115317,997073096,1281953886,3579855332,2724688242,1006888145,1258607687,3524101629,2768942443,901097722,1119000684,3686517206,2898065728,853044451,1172266101,3705015759,2882616665,651767980,1373503546,3369554304,3218104598,565507253,1454621731,3485111705,3099436303,671266974,1594198024,3322730930,2970347812,
795835527,1483230225,3244367275,3060149565,1994146192,31158534,2563907772,4023717930,1907459465,112637215,2680153253,3904427059,2013776290,251722036,2517215374,3775830040,2137656763,141376813,2439277719,3865271297,1802195444,476864866,2238001368,4066508878,1812370925,453092731,2181625025,4111451223,1706088902,314042704,2344532202,4240017532,1658658271,366619977,2362670323,4224994405,1303535960,984961486,2747007092,3569037538,1256170817,1037604311,2765210733,3554079995,1131014506,879679996,2909243462,
3663771856,1141124467,855842277,2852801631,3708648649,1342533948,654459306,3188396048,3373015174,1466479909,544179635,3110523913,3462522015,1591671054,702138776,2966460450,3352799412,1504918807,783551873,3082640443,3233442989,3988292384,2596254646,62317068,1957810842,3939845945,2647816111,81470997,1943803523,3814918930,2489596804,225274430,2053790376,3826175755,2466906013,167816743,2097651377,4027552580,2265490386,503444072,1762050814,4150417245,2154129355,426522225,1852507879,4275313526,2312317920,
282753626,1742555852,4189708143,2394877945,397917763,1622183637,3604390888,2714866558,953729732,1340076626,3518719985,2797360999,1068828381,1219638859,3624741850,2936675148,906185462,1090812512,3747672003,2825379669,829329135,1181335161,3412177804,3160834842,628085408,1382605366,3423369109,3138078467,570562233,1426400815,3317316542,2998733608,733239954,1555261956,3268935591,3050360625,752459403,1541320221,2607071920,3965973030,1969922972,40735498,2617837225,3943577151,1913087877,83908371,2512341634,
3803740692,2075208622,213261112,2463272603,3855990285,2094854071,198958881,2262029012,4057260610,1759359992,534414190,2176718541,4139329115,1873836001,414664567,2282248934,4279200368,1711684554,285281116,2405801727,4167216745,1634467795,376229701,2685067896,3608007406,1308918612,956543938,2808555105,3495958263,1231636301,1047427035,2932959818,3654703836,1088359270,936918E3,2847714899,3736837829,1202900863,817233897,3183342108,3401237130,1404277552,615818150,3134207493,3453421203,1423857449,601450431,
3009837614,3294710456,1567103746,711928724,3020668471,3272380065,1510334235,755167117],p=function(a){var b=[];return b.push(a.slice(0,8)),b.push(a.slice(8,12)),b.push(a.slice(12,16)),b.push(a.slice(16,20)),b.push(a.slice(20,32)),b.join("-")},x=c("./node_modules/@nll/utils/esm/misc.js"),N=Object(x.c)();b=function(){function a(){this._enabled=!1}return a.prototype.disable=function(){this._enabled=!1},a.prototype.enable=function(){this._enabled=!0},a.prototype.log=function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=
arguments[b];this._enabled&&Object(x.a)(function(){N.console.log("%cNortonLifeLock: [info]: "+a.join(" "),"color: #bada55")})},a.prototype.info=function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];this._enabled&&Object(x.a)(function(){N.console.log("%cNortonLifeLock: [info]: "+a.join(" "),"color: #bada55")})},a.prototype.warn=function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];this._enabled&&Object(x.a)(function(){N.console.log("%cNortonLifeLock: [warn]: "+a.join(" "),
"color: #ffeead")})},a.prototype.error=function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];this._enabled&&Object(x.a)(function(){N.console.log("%cNortonLifeLock: [error]: "+a.join(" "),"color: #ff6f69")})},a}();N.__NORTONLIFELOCK__=N.__NORTONLIFELOCK__||{};var ha=N.__NORTONLIFELOCK__.logger||(N.__NORTONLIFELOCK__.logger=new b);X.regex=/^data:((?:\w+\/(?:(?!;).)+)?)((?:;[\w\W]*?[^;])*),(.+)$/i;c.d(a,"fromDataURL",function(){return D});c.d(a,"dataURLtoBlob",function(){return J});c.d(a,
"colors",function(){return k});c.d(a,"crc32",function(){return B});c.d(a,"NortonError",function(){return Y});c.d(a,"fetchTimeout",function(){return O});c.d(a,"formatUUID",function(){return p});c.d(a,"isError",function(){return d});c.d(a,"isErrorEvent",function(){return e});c.d(a,"isDOMError",function(){return g});c.d(a,"isDOMException",function(){return n});c.d(a,"isString",function(){return u});c.d(a,"isPrimitive",function(){return q});c.d(a,"isPlainObject",function(){return t});c.d(a,"isEvent",
function(){return v});c.d(a,"isElement",function(){return w});c.d(a,"isRegExp",function(){return l});c.d(a,"isThenable",function(){return r});c.d(a,"isSyntheticEvent",function(){return y});c.d(a,"logger",function(){return ha});c.d(a,"makeID",function(){return K});c.d(a,"isNodeEnv",function(){return x.d});c.d(a,"dynamicRequire",function(){return x.b});c.d(a,"getGlobalObject",function(){return x.c});c.d(a,"consoleSandbox",function(){return x.a});c.d(a,"fromEntries",function(){return R});c.d(a,"isEmpty",
function(){return C});c.d(a,"isNull",function(){return h});c.d(a,"getOsInfo",function(){return m});c.d(a,"formatPhoneNumber",function(){return z});c.d(a,"phoneAlphConvert",function(){return Z});c.d(a,"setPrototypeOf",function(){return E});c.d(a,"PromiseBuffer",function(){return f});c.d(a,"SyncPromise",function(){return M});c.d(a,"timeoutPromise",function(){return A});c.d(a,"supportsErrorEvent",function(){return T});c.d(a,"supportsDOMError",function(){return P});c.d(a,"supportsDOMException",function(){return L});
c.d(a,"supportsFetch",function(){return I});c.d(a,"supportsBeacon",function(){return ba});c.d(a,"supportsNativeFetch",function(){return ca});c.d(a,"supportsReportingObserver",function(){return G});c.d(a,"supportsReferrerPolicy",function(){return U});c.d(a,"supportsHistory",function(){return V});c.d(a,"getPingTimestamp",function(){return da});c.d(a,"urlEncode",function(){return W});c.d(a,"isDataURL",function(){return X});c.d(a,"uuid",function(){return ea});c.d(a,"uuid4",function(){return fa})},"./node_modules/@nll/utils/esm/misc.js":function(b,
a,c){(function(b,e){function d(){return"[object process]"===Object.prototype.toString.call(void 0!==b?b:0)}function n(a,b){return a.require(b)}function u(){return d()?e:"undefined"!=typeof window?window:"undefined"!=typeof self?self:t}function q(a){var b=u();if(!("console"in b))return a();var c=b.console,d={};"debug info warn error log assert".split(" ").forEach(function(a){a in b.console&&c[a].__nortonlifelock__&&(d[a]=c[a].__norton_wrapped__,c[a]=c[a].__norton_wrapped__)});a=a();return Object.keys(d).forEach(function(a){c[a]=
d[a]}),a}c.d(a,"d",function(){return d});c.d(a,"b",function(){return n});c.d(a,"c",function(){return u});c.d(a,"a",function(){return q});var t={}}).call(this,c("./node_modules/process/browser.js"),c("./node_modules/webpack/buildin/global.js"))},"./node_modules/process/browser.js":function(b,a){function c(){throw Error("setTimeout has not been defined");}function d(){throw Error("clearTimeout has not been defined");}function e(a){if(t===setTimeout)return setTimeout(a,0);if((t===c||!t)&&setTimeout)return t=
setTimeout,setTimeout(a,0);try{return t(a,0)}catch(O){try{return t.call(null,a,0)}catch(D){return t.call(this,a,0)}}}function g(){r&&w&&(r=!1,w.length?l=w.concat(l):y=-1,l.length&&n())}function n(){if(!r){var a=e(g);r=!0;for(var b=l.length;b;){w=l;for(l=[];++y<b;)w&&w[y].run();y=-1;b=l.length}w=null;r=!1;(function(a){if(v===clearTimeout)return clearTimeout(a);if((v===d||!v)&&clearTimeout)return v=clearTimeout,clearTimeout(a);try{v(a)}catch(J){try{return v.call(null,a)}catch(B){return v.call(this,
a)}}})(a)}}function u(a,b){this.fun=a;this.array=b}function q(){}b=b.exports={};try{var t="function"==typeof setTimeout?setTimeout:c}catch(A){t=c}try{var v="function"==typeof clearTimeout?clearTimeout:d}catch(A){v=d}!0;var w,l=[],r=!1,y=-1;b.nextTick=function(a){var b=Array(arguments.length-1);if(1<arguments.length)for(var c=1;c<arguments.length;c++)b[c-1]=arguments[c];l.push(new u(a,b));1!==l.length||r||e(n)};u.prototype.run=function(){this.fun.apply(null,this.array)};b.title="browser";b.browser=
!0;b.env={};b.argv=[];b.version="";b.versions={};b.on=q;b.addListener=q;b.once=q;b.off=q;b.removeListener=q;b.removeAllListeners=q;b.emit=q;b.prependListener=q;b.prependOnceListener=q;b.listeners=function(a){return[]};b.binding=function(a){throw Error("process.binding is not supported");};b.cwd=function(){return"/"};b.chdir=function(a){throw Error("process.chdir is not supported");};b.umask=function(){return 0}},"./node_modules/tslib/tslib.es6.js":function(b,a,c){function d(a,b){function c(){this.constructor=
a}R(a,b);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)}function e(a,b){var c={},d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&0>b.indexOf(d)&&(c[d]=a[d]);if(null!=a&&"function"==typeof Object.getOwnPropertySymbols){var e=0;for(d=Object.getOwnPropertySymbols(a);e<d.length;e++)0>b.indexOf(d[e])&&(c[d[e]]=a[d[e]])}return c}function g(a,b,c,d){var e,h=arguments.length,g=3>h?b:null===d?d=Object.getOwnPropertyDescriptor(b,c):d;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)g=
Reflect.decorate(a,b,c,d);else for(var m=a.length-1;0<=m;m--)(e=a[m])&&(g=(3>h?e(g):3<h?e(b,c,g):e(b,c))||g);return 3<h&&g&&Object.defineProperty(b,c,g),g}function n(a,b){return function(c,d){b(c,d,a)}}function u(a,b){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(a,b)}function q(a,b,c,d){return new (c||(c=Promise))(function(e,h){function g(a){try{z(d.next(a))}catch(G){h(G)}}function m(a){try{z(d.throw(a))}catch(G){h(G)}}function z(a){a.done?e(a.value):(new c(function(b){b(a.value)})).then(g,
m)}z((d=d.apply(a,b||[])).next())})}function t(a,b){function c(c){return function(g){return function(c){if(d)throw new TypeError("Generator is already executing.");for(;m;)try{if(d=1,e&&(h=2&c[0]?e.return:c[0]?e.throw||((h=e.return)&&h.call(e),0):e.next)&&!(h=h.call(e,c[1])).done)return h;switch(e=0,h&&(c=[2&c[0],h.value]),c[0]){case 0:case 1:h=c;break;case 4:return m.label++,{value:c[1],done:!1};case 5:m.label++;e=c[1];c=[0];continue;case 7:c=m.ops.pop();m.trys.pop();continue;default:if(!(h=0<(h=
m.trys).length&&h[h.length-1])&&(6===c[0]||2===c[0])){m=0;continue}if(3===c[0]&&(!h||c[1]>h[0]&&c[1]<h[3]))m.label=c[1];else if(6===c[0]&&m.label<h[1])m.label=h[1],h=c;else if(h&&m.label<h[2])m.label=h[2],m.ops.push(c);else{h[2]&&m.ops.pop();m.trys.pop();continue}}c=b.call(a,m)}catch(U){c=[6,U],e=0}finally{d=h=0}if(5&c[0])throw c[1];return{value:c[0]?c[1]:void 0,done:!0}}([c,g])}}var d,e,h,g,m={label:0,sent:function(){if(1&h[0])throw h[1];return h[1]},trys:[],ops:[]};$jscomp.initSymbol();$jscomp.initSymbol();
$jscomp.initSymbolIterator();return g={next:c(0),throw:c(1),return:c(2)},"function"==typeof Symbol&&(g[Symbol.iterator]=function(){return this}),g}function v(a,b){for(var c in a)b.hasOwnProperty(c)||(b[c]=a[c])}function w(a){$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b="function"==typeof Symbol&&a[Symbol.iterator],c=0;return b?b.call(a):{next:function(){return a&&c>=a.length&&(a=void 0),{value:a&&a[c++],done:!a}}}}function l(a,b){$jscomp.initSymbol();$jscomp.initSymbol();
$jscomp.initSymbolIterator();var c="function"==typeof Symbol&&a[Symbol.iterator];if(!c)return a;var d;a=c.call(a);var e=[];try{for(;(void 0===b||0<b--)&&!(d=a.next()).done;)e.push(d.value)}catch(L){var h={error:L}}finally{try{d&&!d.done&&(c=a.return)&&c.call(a)}finally{if(h)throw h.error;}}return e}function r(){for(var a=[],b=0;b<arguments.length;b++)a=a.concat(l(arguments[b]));return a}function y(a){return this instanceof y?(this.v=a,this):new y(a)}function A(a,b,c){function d(a){z[a]&&(l[a]=function(b){return new Promise(function(c,
d){1<n.push([a,b,c,d])||e(a,b)})})}function e(a,b){try{(c=z[a](b)).value instanceof y?Promise.resolve(c.value.v).then(h,g):m(n[0][2],c)}catch(W){m(n[0][3],W)}var c}function h(a){e("next",a)}function g(a){e("throw",a)}function m(a,b){a(b);n.shift();n.length&&e(n[0][0],n[0][1])}$jscomp.initSymbol();$jscomp.initSymbolAsyncIterator();if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");var l,z=c.apply(a,b||[]),n=[];$jscomp.initSymbol();$jscomp.initSymbolAsyncIterator();
return l={},d("next"),d("throw"),d("return"),l[Symbol.asyncIterator]=function(){return this},l}function O(a){function b(b,e){c[b]=a[b]?function(c){return(d=!d)?{value:y(a[b](c)),done:"return"===b}:e?e(c):c}:e}var c,d;$jscomp.initSymbol();$jscomp.initSymbolIterator();return c={},b("next"),b("throw",function(a){throw a;}),b("return"),c[Symbol.iterator]=function(){return this},c}function D(a){function b(b){c[b]=a[b]&&function(c){return new Promise(function(d,e){(function(a,b,c,d){Promise.resolve(d).then(function(b){a({value:b,
done:c})},b)})(d,e,(c=a[b](c)).done,c.value)})}}$jscomp.initSymbol();$jscomp.initSymbolAsyncIterator();if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");$jscomp.initSymbol();$jscomp.initSymbolAsyncIterator();var c,d=a[Symbol.asyncIterator];$jscomp.initSymbol();$jscomp.initSymbolAsyncIterator();return d?d.call(a):(a=w(a),c={},b("next"),b("throw"),b("return"),c[Symbol.asyncIterator]=function(){return this},c)}function J(a,b){return Object.defineProperty?Object.defineProperty(a,
"raw",{value:b}):a.raw=b,a}function B(a){if(a&&a.__esModule)return a;var b={};if(null!=a)for(var c in a)Object.hasOwnProperty.call(a,c)&&(b[c]=a[c]);return b.default=a,b}function K(a){return a&&a.__esModule?a:{default:a}}c.r(a);c.d(a,"__extends",function(){return d});c.d(a,"__assign",function(){return C});c.d(a,"__rest",function(){return e});c.d(a,"__decorate",function(){return g});c.d(a,"__param",function(){return n});c.d(a,"__metadata",function(){return u});c.d(a,"__awaiter",function(){return q});
c.d(a,"__generator",function(){return t});c.d(a,"__exportStar",function(){return v});c.d(a,"__values",function(){return w});c.d(a,"__read",function(){return l});c.d(a,"__spread",function(){return r});c.d(a,"__await",function(){return y});c.d(a,"__asyncGenerator",function(){return A});c.d(a,"__asyncDelegator",function(){return O});c.d(a,"__asyncValues",function(){return D});c.d(a,"__makeTemplateObject",function(){return J});c.d(a,"__importStar",function(){return B});c.d(a,"__importDefault",function(){return K});
var R=function(a,b){return(R=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])})(a,b)},C=function(){return(C=Object.assign||function(a){for(var b,c=1,d=arguments.length;c<d;c++)for(var e in b=arguments[c])Object.prototype.hasOwnProperty.call(b,e)&&(a[e]=b[e]);return a}).apply(this,arguments)}},"./node_modules/webpack/buildin/global.js":function(b,a){a=function(){return this}();try{a=a||(new Function("return this"))()}catch(c){"object"==
typeof window&&(a=window)}b.exports=a},"./source/HBIndex.js":function(b,a,c){c.r(a);var d={portal:"WEB_APPLICATION",mobile:"MOBILE_APPLICATION",extension:"BROWSER_EXTENSION"},e=SymBfw.telemetryConstants.parameters.CUSTOM_DIMENSION2,g=SymBfw.telemetryConstants.parameters.CUSTOM_DIMENSION6,n={INSTALL:"install",HEARTBEAT:"heartbeat"};b=SymBfw.utils;var u=b.isObject,q=b.isFunction,t=b.isString,v=SymBfw.logger.error,w=function(){this._userLang=this._apiKey=this._dataSource=this._machineId=this._prodVersion=
this._prodName=null;this._retryIntervalMillis=864E5;this.install={};this.install.isInstallPingEnabled=!0;this.install.isFreshInstall=null;this.heartBeat={};this.heartBeat.isHeartBeatPingEnabled=!0;this.heartBeat.heartBeatIntervalInMilliSec=null;this._isLocalStorageNeeded=!1};$jscomp.global.Object.defineProperties(w.prototype,{prodName:{configurable:!0,enumerable:!0,set:function(a){this._prodName=a},get:function(){return this._prodName}},prodVersion:{configurable:!0,enumerable:!0,set:function(a){this._prodVersion=
a},get:function(){return this._prodVersion}},machineId:{configurable:!0,enumerable:!0,set:function(a){this._machineId=a},get:function(){return this._machineId}},apiKey:{configurable:!0,enumerable:!0,set:function(a){this._apiKey=a},get:function(){return this._apiKey}},dataSource:{configurable:!0,enumerable:!0,set:function(a){this._dataSource=d[a]},get:function(){return this._dataSource}},userLanguage:{configurable:!0,enumerable:!0,set:function(a){this._userLang=a},get:function(){return this._userLang}},
retryIntervalMillis:{configurable:!0,enumerable:!0,set:function(a){this._retryIntervalMillis=a},get:function(){return this._retryIntervalMillis}},isInstallPingEnabled:{configurable:!0,enumerable:!0,set:function(a){this.install.isInstallPingEnabled=a},get:function(){return this.install.isInstallPingEnabled}},isFreshInstall:{configurable:!0,enumerable:!0,set:function(a){this.install.isFreshInstall=a},get:function(){return this.install.isFreshInstall}},isHeartBeatPingEnabled:{configurable:!0,enumerable:!0,
set:function(a){this.heartBeat.isHeartBeatPingEnabled=a},get:function(){return this.heartBeat.isHeartBeatPingEnabled}},heartBeatIntervalInMilliSec:{configurable:!0,enumerable:!0,set:function(a){this.heartBeat.heartBeatIntervalInMilliSec=a},get:function(){return this.heartBeat.heartBeatIntervalInMilliSec}},isLocalStorageNeeded:{configurable:!0,enumerable:!0,set:function(a){this._isLocalStorageNeeded=a},get:function(){return this._isLocalStorageNeeded}},additionalInstallPingParams:{configurable:!0,
enumerable:!0,set:function(a){if(u(a)){for(var b in a)t(b)||v("custom dimension value should be a string"),q(a[b])||v(a[b]+"is not a function");this._additionalInstallPingParams=a}},get:function(){return this._additionalInstallPingParams}},additionalHeartBeatPingParams:{configurable:!0,enumerable:!0,set:function(a){if(u(a)){for(var b in a)t(b)||v("custom dimension value should be a string"),q(a[b])||v(a[b]+"is not a function");this._additionalHeartBeatPingParams=a}},get:function(){return this._additionalHeartBeatPingParams}}});
b=function(){};b.prototype.perform=function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){throw Error("Derived class needs to implement this function");})};var l=function(){this._container={}};l.prototype.loadContainer=function(a){var b=this;return new Promise(function(c,f){b.isLocalStorageNeeded=a;b.isLocalStorageNeeded?(b.container=window.localStorage,c(!0)):SymBfw.settings.loadSettingsContainer("HEARTBEAT_SDK_CONTAINER",!0,function(a,d,e){(!1===a||SymBfw.utils.isNil(d))&&f(e);
b.container=d;c(!0)})})};l.prototype.getContainerByName=function(a){if(SymBfw.utils.isNil(a)||SymBfw.utils.isNil(this.container))throw Error("Unable to retrieve the container value");return this.isLocalStorageNeeded?this.container.getItem(a):this.container.getObject(a)};l.prototype.setContainerByName=function(a,b){if(SymBfw.utils.isNil(a)||SymBfw.utils.isNil(this.container))throw Error("Unable to set the container value");this.isLocalStorageNeeded?this.container.setItem(a,b):this.container.setObject(a,
b)};$jscomp.global.Object.defineProperties(l.prototype,{container:{configurable:!0,enumerable:!0,get:function(){return this._container.storage},set:function(a){this._container.storage=a}},isLocalStorageNeeded:{configurable:!0,enumerable:!0,get:function(){return this._container.isLocalStorageNeeded},set:function(a){this._container.isLocalStorageNeeded=a}}});var r=Object.freeze(new l),y=SymBfw.utils.isNil;l=function(){this.defaultParameters={};this.userLang=this.apiKey=this.dataSource=this.machineId=
this.prodVersion=this.prodName=null};l.prototype.init=function(a){if(y(a)||0===Object.keys(a).length)throw Error("configObj cannot be null");this.prodName=a.prodName;this.prodVersion=a.prodVersion;this.machineId=a.machineId;this.dataSource=a.dataSource;this.apiKey=a.apiKey;this.userLang=a.userLanguage};l.prototype._constructQueryParams=function(a){var b="";a=$jscomp.makeIterator(Object.entries(a));for(var c=a.next();!c.done;c=a.next()){var f=$jscomp.makeIterator(c.value);c=f.next().value;f=f.next().value;
b+=c+"="+f+"&"}return b.substring(0,b.length-1)};l.prototype._constructDefaultParams=function(){var a={};return this.defaultParameters=(a.an=this.prodName,a.av=this.prodVersion,a.cid=this.machineId,a.ds=this.dataSource,a.tid=this.apiKey,a.ul=this.userLang,a.v=1,a.aip=1,a.t="event",a[e]=this.machineId,a[g]=SymBfw.globals.BROWSER,a),this._constructQueryParams(this.defaultParameters)};l.prototype.send=function(a){var b=this,c,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress){if(y(a))return d.return(Promise.reject("parameters are required for sending telemetry events"));
c=b._constructDefaultParams();c+="&"+b._constructQueryParams(a);f={method:"POST",body:c};d.setCatchFinallyBlocks(2);return d.yield(fetch("https://www.google-analytics.com/collect",f),4)}if(2!=d.nextAddress)return d.return(200===d.yieldResult.status?Promise.resolve("telemetry sent successfully"):Promise.reject("Error in sending telemetry"));d.enterCatchBlock();return d.return(Promise.reject("Error in sending telemetry"))})};var A=new l,O=SymBfw.utils.isntNil,D=function(){this._additionalHeartBeatPingParams=
this._updateInterval=this._hbPingRetryInterval=this._hbPingInterval=this._containerKeyName=null;return this};$jscomp.inherits(D,b);D.prototype._getCurrentUTCTimestamp=function(){return Math.floor((new Date).getTime())};D.prototype._checkPingTimeArrived=function(){var a=JSON.parse(r.getContainerByName(this._containerKeyName));return!!SymBfw.utils.isNil(a)||a+this._hbPingInterval<this._getCurrentUTCTimestamp()};D.prototype._constructHeartBeatPing=function(){var a=this,b,c,d,e,g,h;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:b=
{};c=(b.ec="UserBase",b.ea="HeartBeat",b);if(!O(a._additionalHeartBeatPingParams)){f.jumpTo(2);break}e=f.forIn(a._additionalHeartBeatPingParams);case 3:if(null==(d=e.getNext())){f.jumpTo(2);break}g=c;h=d;return f.yield(a._additionalHeartBeatPingParams[d](),6);case 6:g[h]=f.yieldResult;f.jumpTo(3);break;case 2:return f.return(c)}})};D.prototype.perform=function(a){var b=this;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){if(SymBfw.utils.isEmptyObject(a))throw Error("HeartBeat ping configuration is empty");
if(b._containerKeyName="hbLastUpdateTimeKey",b._hbPingInterval=a.heartBeatIntervalInMilliSec,b._hbPingRetryInterval=a.retryIntervalMillis,b._updateInterval=a.heartBeatIntervalInMilliSec,b._additionalHeartBeatPingParams=a._additionalHeartBeatPingParams||null,!a.isHeartBeatPingEnabled)return c.jumpTo(0);c.setCatchFinallyBlocks(3);return c.yield(b._sendHeartBeatPing(),5)}if(3!=c.nextAddress)return c.leaveTryBlock(0);c.enterCatchBlock();SymBfw.logger.error("Failed to send the Telemetry");c.jumpToEnd()})};
D.prototype._sendHeartBeatPing=function(){var a=this,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){switch(c.nextAddress){case 1:if(!a._checkPingTimeArrived()){c.jumpTo(2);break}return c.yield(a._constructHeartBeatPing(),3);case 3:return b=c.yieldResult,c.setCatchFinallyBlocks(4),c.yield(A.send(b),6);case 6:r.setContainerByName(a._containerKeyName,a._getCurrentUTCTimestamp());c.leaveTryBlock(2);break;case 4:c.enterCatchBlock(),SymBfw.logger.debug("Failed to send the Telementry and retry interval set");
case 2:setTimeout(function(){a._sendHeartBeatPing()},18E5),c.jumpToEnd()}})};var J=SymBfw.utils,B=function(){this._additionalInstallPingParams=this._container=null;return this};$jscomp.inherits(B,b);B.prototype.perform=function(a){var b=this;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){if(J.isEmptyObject(a))throw Error("Install Ping configuration is missing");if(!a.isInstallPingEnabled)return c.return(!1);b.container=r;if(!b._canTriggerInstallPing(a))return c.jumpTo(2);
b._additionalInstallPingParams=a._additionalInstallPingParams;return c.yield(b._sendInstallPing(),3)}return c.return(!0)})};B.prototype._canTriggerInstallPing=function(a){a=a.isFreshInstall;var b=!1,c=this.container.getContainerByName("installPingStatusKey");if(J.isNil(c)){if(a)return!0;this.container.setContainerByName("installPingStatusKey","0")}else"2"===c&&(b=!0);return b};B.prototype._sendInstallPing=function(){var a=this,b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:return f.yield(a._constructInstallPing(),
2);case 2:return b=f.yieldResult,c=null,f.setCatchFinallyBlocks(3,4),f.yield(A.send(b),6);case 6:c="1";case 4:f.enterFinallyBlock();a.container.setContainerByName("installPingStatusKey",c);f.leaveFinallyBlock(0);break;case 3:f.enterCatchBlock(),c="2",f.jumpTo(4)}})};B.prototype._constructInstallPing=function(){var a=this,b,c,d,e,g,h;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:b={};c=(b.ec="UserBase",b.ea="Install",b);if(!J.isntNil(a._additionalInstallPingParams)){f.jumpTo(2);
break}e=f.forIn(a._additionalInstallPingParams);case 3:if(null==(d=e.getNext())){f.jumpTo(2);break}g=c;h=d;return f.yield(a._additionalInstallPingParams[d](),6);case 6:g[h]=f.yieldResult;f.jumpTo(3);break;case 2:return f.return(c)}})};$jscomp.global.Object.defineProperties(B.prototype,{container:{configurable:!0,enumerable:!0,get:function(){return this._container},set:function(a){this._container=a}}});var K=c("./node_modules/@nll/telemetry/dist/index.js"),R=c("./node_modules/@nll/types/esm/status.js");
c=SymBfw.utils;var C=c.isNil,h=c.isntNil,m=c.isEmptyObject;c=function(){this.initialized=!1};c.prototype.init=function(a){if(m(a)||C(a.prodName)||C(a.prodVersion)||C(a.machineId))throw Error("config object should be valid");var b={};K.init((b.product=a.prodName,b.version=a.prodVersion,b.enabled=!0,b.transport=K.FetchTransport,b));K.setMid(a.machineId);this.initialized=!0};c.prototype._sleep=function(a){return new Promise(function(b){return setTimeout(b,a)})};c.prototype._sendErrorTelemetry=function(a,
b){var c,f,d,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(k){if(1==k.nextAddress)return c="Norton "+a+" Telemetry",k.yield(b.text(),2);f=k.yieldResult;h(f)&&0!==f.length&&(c=c+" - "+f);d=b;e=d.status;h(e)&&(c=c+" - "+e);SymBfw.logger.error(c);k.jumpToEnd()})};c.prototype.send=function(a,b){b=void 0===b?1:b;var c=this,f,d,e,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:if(!c.initialized)throw Error("Please initialize before calling send");
if(m(a)||C(a.ctt)||C(a.E)||C(a.module))throw Error("ping data should be valid");f={};d=Object.assign({},a,(f.cst=(new Date).getTime(),f));e={};g.setCatchFinallyBlocks(2);return g.yield(K.ping(d),4);case 4:e=g.yieldResult;g.leaveTryBlock(3);break;case 2:g.enterCatchBlock(),SymBfw.logger.debug("Telemetry.ping rejected the ping call");case 3:if(C(e)||C(e.status))throw Error("Error in sending Telemetry");if(e.status===R.a.Success)return g.return("Norton Ping sent successfully");if(1>=b)throw h(e.response)&&
(k=a.E,c._sendErrorTelemetry(k,e.response)),Error("Error in sending Telemetry");return g.yield(c._sleep(5E3),5);case 5:return g.return(c.send(a,b-1))}})};var z=new c,Z=SymBfw.utils;c=function(){};c.prototype.perform=function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){throw Error("Derived class needs to implement this function");})};c.prototype.constructPingObject=function(a,b,c){var f,d,e,k,g,h,l,m,q,r;return $jscomp.asyncExecutePromiseGeneratorProgram(function(p){switch(p.nextAddress){case 1:if(!Object.values(n).includes(a)||
Z.isNil(b))throw Error("pass valid arguments");f={};d=(f.module=b,f.E=a,f.ctt=(new Date).getTime(),f);if(!Z.isntNil(c)){p.jumpTo(2);break}e=$jscomp.makeIterator(Object.entries(c));k=e.next();case 3:if(k.done){p.jumpTo(2);break}g=k.value;h=$jscomp.makeIterator(g);l=h.next().value;m=h.next().value;p.setCatchFinallyBlocks(6);q=d;r=l;return p.yield(m(),8);case 8:q[r]=p.yieldResult;p.leaveTryBlock(4);break;case 6:throw p.enterCatchBlock(),Error("error in additional ping parameters");case 4:k=e.next();
p.jumpTo(3);break;case 2:return p.return(d)}})};var T=SymBfw.utils,P=function(){this._additionalInstallPingParams=this._module=null;return this};$jscomp.inherits(P,c);P.prototype.perform=function(a){if(T.isEmptyObject(a)||T.isNil(a.module))throw Error("config object should be valid");this._canTriggerInstallPing(a)&&(this._module=a.module,this._additionalInstallPingParams=a._additionalInstallPingParams||null,this._sendInstallPing())};P.prototype._canTriggerInstallPing=function(a){if(!a.isInstallPingEnabled)return!1;
var b=!1,c=r.getContainerByName("nortonInstallPingStatusKey");if(T.isNil(c)){if(a.isFreshInstall)return!0;r.setContainerByName("nortonInstallPingStatusKey","0")}else"2"===c&&(b=!0);return b};P.prototype._sendInstallPing=function(){var a=this,b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:return b=null,f.setCatchFinallyBlocks(2,3),f.yield(a.constructPingObject(n.INSTALL,a._module,a._additionalInstallPingParams),5);case 5:return c=f.yieldResult,f.yield(z.send(c),
6);case 6:b="1";case 3:f.enterFinallyBlock();r.setContainerByName("nortonInstallPingStatusKey",b);f.leaveFinallyBlock(0);break;case 2:f.enterCatchBlock(),b="2",f.jumpTo(3)}})};var L=SymBfw.utils,I=function(){this._module=this._hbPingInterval=this._additionalHeartBeatPingParams=null;return this};$jscomp.inherits(I,c);I.prototype.perform=function(a){if(L.isEmptyObject(a)||L.isNil(a.heartBeatIntervalInMilliSec)||L.isNil(a.module))throw Error("HeartBeat ping configuration is not valid");a.isHeartBeatPingEnabled&&
(this._hbPingInterval=a.heartBeatIntervalInMilliSec,this._module=a.module,this._additionalHeartBeatPingParams=a._additionalHeartBeatPingParams||null,this._sendHeartBeatPing())};I.prototype._checkPingTimeArrived=function(){var a=JSON.parse(r.getContainerByName("nortonHBLastUpdateTimeKey"));return!!L.isNil(a)||a+this._hbPingInterval<(new Date).getTime()};I.prototype._sendHeartBeatPing=function(){var a=this,b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:if(!a._checkPingTimeArrived()){f.jumpTo(2);
break}f.setCatchFinallyBlocks(3);return f.yield(a.constructPingObject(n.HEARTBEAT,a._module,a._additionalHeartBeatPingParams),5);case 5:return b=f.yieldResult,f.yield(z.send(b),6);case 6:r.setContainerByName("nortonHBLastUpdateTimeKey",(new Date).getTime());f.leaveTryBlock(2);break;case 3:c=f.enterCatchBlock(),SymBfw.logger.debug("Failed to send heartbeat ping. Reason - "+c.message);case 2:setTimeout(function(){a._sendHeartBeatPing()},18E5),f.jumpToEnd()}})};c=SymBfw.utils;var ba=c.isObject,ca=c.isFunction,
G=function(){this._module=this._machineId=this._prodVersion=this._prodName=null;this._retryIntervalMillis=864E5;this.install={};this.install.isInstallPingEnabled=!0;this.install.isFreshInstall=null;this.heartBeat={};this.heartBeat.isHeartBeatPingEnabled=!0;this.heartBeat.heartBeatIntervalInMilliSec=null;this._isLocalStorageNeeded=!1};G.prototype._validateAdditionalParams=function(a){if(!ba(a))return!1;a=$jscomp.makeIterator(Object.entries(a));for(var b=a.next();!b.done;b=a.next())if(b=$jscomp.makeIterator(b.value),
b.next(),b=b.next().value,!ca(b))return!1;return!0};$jscomp.global.Object.defineProperties(G.prototype,{prodName:{configurable:!0,enumerable:!0,set:function(a){this._prodName=a},get:function(){return this._prodName}},prodVersion:{configurable:!0,enumerable:!0,set:function(a){this._prodVersion=a},get:function(){return this._prodVersion}},machineId:{configurable:!0,enumerable:!0,set:function(a){this._machineId=a},get:function(){return this._machineId}},module:{configurable:!0,enumerable:!0,set:function(a){this._module=
a},get:function(){return this._module}},retryIntervalMillis:{configurable:!0,enumerable:!0,set:function(a){this._retryIntervalMillis=a},get:function(){return this._retryIntervalMillis}},isInstallPingEnabled:{configurable:!0,enumerable:!0,set:function(a){this.install.isInstallPingEnabled=a},get:function(){return this.install.isInstallPingEnabled}},isFreshInstall:{configurable:!0,enumerable:!0,set:function(a){this.install.isFreshInstall=a},get:function(){return this.install.isFreshInstall}},isHeartBeatPingEnabled:{configurable:!0,
enumerable:!0,set:function(a){this.heartBeat.isHeartBeatPingEnabled=a},get:function(){return this.heartBeat.isHeartBeatPingEnabled}},heartBeatIntervalInMilliSec:{configurable:!0,enumerable:!0,set:function(a){this.heartBeat.heartBeatIntervalInMilliSec=a},get:function(){return this.heartBeat.heartBeatIntervalInMilliSec}},isLocalStorageNeeded:{configurable:!0,enumerable:!0,set:function(a){this._isLocalStorageNeeded=a},get:function(){return this._isLocalStorageNeeded}},additionalInstallPingParams:{configurable:!0,
enumerable:!0,set:function(a){this._additionalInstallPingParams=this._validateAdditionalParams(a)?a:null},get:function(){return this._additionalInstallPingParams}},additionalHeartBeatPingParams:{configurable:!0,enumerable:!0,set:function(a){this._additionalHeartBeatPingParams=this._validateAdditionalParams(a)?a:null},get:function(){return this._additionalHeartBeatPingParams}}});var U=SymBfw.utils;c=function(){};c.prototype.init=function(a){var b=this,c,d,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==
e.nextAddress){if(!(a instanceof w&&b._isValidConfigObj(a)))throw new TypeError("HeartBeat SDK initialization Failed - Invalid Configuration Object");e.setCatchFinallyBlocks(2);c=a;d=c.isLocalStorageNeeded;return e.yield(r.loadContainer(d),4)}if(2!=e.nextAddress)return A.init(a),(new B).perform(a),(new D).perform(a),e.leaveTryBlock(0);f=e.enterCatchBlock();SymBfw.logger.error("HB initialization Failed :",f.message);e.jumpToEnd()})};c.prototype.initNortonPing=function(a){var b=this,c,d,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==
e.nextAddress){if(!(a instanceof G&&b._isValidConfigObj(a)))throw new TypeError("HB Norton Ping initialization Failed - Invalid Configuration Object");e.setCatchFinallyBlocks(2);c=a;d=c.isLocalStorageNeeded;return e.yield(r.loadContainer(d),4)}if(2!=e.nextAddress)return z.init(a),(new P).perform(a),(new I).perform(a),e.leaveTryBlock(0);f=e.enterCatchBlock();SymBfw.logger.error("HB Norton Ping initialization Failed : "+f.message);e.jumpToEnd()})};c.prototype._isValidConfigObj=function(a){a=Object.values(a);
for(var b in a)if(a[b]instanceof Object){if(!this._isValidConfigObj(a[b]))return!1}else if(U.isNil(a[b]))return!1;return!0};c=new c;var V=function(){this._userLanguage=this._apiKey=this._dataSource=this._machineId=this._prodVersion=this._prodName=null;this._isLocalStorageNeeded=!1;this._pingData=this._pingName=this._isMOTEnabled=this._pingIntervalInMillis=null};$jscomp.global.Object.defineProperties(V.prototype,{prodName:{configurable:!0,enumerable:!0,set:function(a){this._prodName=a},get:function(){return this._prodName}},
prodVersion:{configurable:!0,enumerable:!0,set:function(a){this._prodVersion=a},get:function(){return this._prodVersion}},machineId:{configurable:!0,enumerable:!0,set:function(a){this._machineId=a},get:function(){return this._machineId}},apiKey:{configurable:!0,enumerable:!0,set:function(a){this._apiKey=a},get:function(){return this._apiKey}},dataSource:{configurable:!0,enumerable:!0,set:function(a){this._dataSource=d[a]},get:function(){return this._dataSource}},userLanguage:{configurable:!0,enumerable:!0,
set:function(a){this._userLanguage=a},get:function(){return this._userLanguage}},isLocalStorageNeeded:{configurable:!0,enumerable:!0,set:function(a){this._isLocalStorageNeeded=a},get:function(){return this._isLocalStorageNeeded}},pingIntervalInMillis:{configurable:!0,enumerable:!0,set:function(a){this._pingIntervalInMillis=a},get:function(){return this._pingIntervalInMillis}},isMOTEnabled:{configurable:!0,enumerable:!0,set:function(a){this._isMOTEnabled=a},get:function(){return this._isMOTEnabled}},
pingName:{configurable:!0,enumerable:!0,set:function(a){this._pingName=a},get:function(){return this._pingName}},pingData:{configurable:!0,enumerable:!0,set:function(a){this._pingData=a},get:function(){return this._pingData}}});l=SymBfw.utils;var da=l.isNil,W=l.isntNil,X=l.isInteger,ea=l.isString,fa=l.isObject,S=l.isEmptyObject,E=function(){this._pollTimer=this._pingData=this._hbRecurrentPingInterval=this._containerKeyName=null;return this};$jscomp.inherits(E,b);E.prototype.init=function(a){if(S(a))throw Error("recurrentPingConfig cannot be null");
if(!X(a._pingIntervalInMillis))throw Error("ping interval should be an integer");if(!ea(a._pingName))throw Error("invalid ping name");if(!fa(a._pingData))throw Error("invalid ping data");this._hbRecurrentPingInterval=a._pingIntervalInMillis;this._pingData=a._pingData;this._containerKeyName=a._pingName+"_lastupdatetime"};E.prototype._checkPingTimeReached=function(){var a=JSON.parse(r.getContainerByName(this._containerKeyName));return!!da(a)||a+this._hbRecurrentPingInterval<this._getCurrentUTCTimestamp()};
E.prototype.perform=function(){var a=this;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return a._checkPingTimeReached()?b.yield(a._sendTelemetry(),3):b.jumpTo(2);a._pollTimer=setTimeout(function(){a.perform()},18E5);b.jumpToEnd()})};E.prototype._sendTelemetry=function(){var a=this;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return b.setCatchFinallyBlocks(2),b.yield(A.send(a._pingData),4);if(2!=b.nextAddress)return r.setContainerByName(a._containerKeyName,
a._getCurrentUTCTimestamp()),b.leaveTryBlock(0);b.enterCatchBlock();SymBfw.logger.error("Failed to send the recurrent ping and retry interval set");b.jumpToEnd()})};E.prototype.stop=function(){W(this._pollTimer)&&(clearTimeout(this._pollTimer),this._pollTimer=null)};E.prototype._getCurrentUTCTimestamp=function(){return Math.floor((new Date).getTime())};b=SymBfw.utils;var F=b.isString,Y=b.isNil,M=b.isEmptyObject;b=function(){this._pingObjMap={}};b.prototype.init=function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){a.jumpToEnd()})};
b.prototype.createPing=function(a){var b=this,c,d,e,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){if(1==g.nextAddress){if(!(a instanceof V))throw new TypeError("Active vault user ping initialization failed - Invalid Configuration Object");if(Y(a._isLocalStorageNeeded)||Y(a._pingName))throw Error("config object values cannot be empty");g.setCatchFinallyBlocks(2);c=a;d=c.isLocalStorageNeeded;return g.yield(r.loadContainer(d),4)}if(2!=g.nextAddress){if(!M(b._pingObjMap[a._pingName]))throw Error(a._pingName+
" already exists");e=new E;e.init(a);b._pingObjMap[a._pingName]=e;A.init(a);return g.leaveTryBlock(0)}f=g.enterCatchBlock();SymBfw.logger.error("Recurrent Ping Creation Failed :",f.message);g.jumpToEnd()})};b.prototype.start=function(a){if(!F(a))throw Error("Invalid ping name");a=this._pingObjMap[a];if(M(a))throw Error("Invalid ping object");a.perform()};b.prototype.stop=function(a){if(!F(a))throw Error("Invalid ping name");a=this._pingObjMap[a];if(M(a))throw Error("Invalid ping object");a.stop()};
b=new b;a.default={hbManager:c,HBConfig:w,HBRecurrentPingConfig:V,hbRecurrentPingManager:b,HBNortonPingConfig:G}},0:function(b,a,c){b.exports=c("./source/HBIndex.js")}}).default});
