var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,e=[];!(b=a.next()).done;)e.push(b.value);return e};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){a!=Array.prototype&&a!=Object.prototype&&(a[b]=e.value)};$jscomp.polyfill=function(a,b,e,f){if(b){e=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var g=a[f];g in e||(e[g]={});e=e[g]}a=a[a.length-1];f=e[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function e(a){return a instanceof g?a:new g(function(b,h){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){f(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var h=a[b];a[b]=null;try{h()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var g=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};g.prototype.createResolveAndReject_=function(){function a(a){return function(c){h||(h=!0,a.call(b,c))}}var b=this,h=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};g.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof g)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};g.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};g.prototype.reject_=function(a){this.settle_(2,a)};g.prototype.fulfill_=function(a){this.settle_(1,a)};g.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};g.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)d.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var d=new b;g.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};g.prototype.settleSameAsThenable_=function(a,b){var h=this.createResolveAndReject_();try{a.call(b,h.resolve,h.reject)}catch(n){h.reject(n)}};g.prototype.then=function(a,b){function h(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(v){c(v)}}:b}var d,c,e=new g(function(a,b){d=a;c=b});this.callWhenSettled_(h(a,d),h(b,c));return e};
g.prototype.catch=function(a){return this.then(void 0,a)};g.prototype.callWhenSettled_=function(a,b){function h(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?d.asyncExecute(h):this.onSettledCallbacks_.push(h)};g.resolve=e;g.reject=function(a){return new g(function(b,h){h(a)})};g.race=function(a){return new g(function(b,h){for(var d=$jscomp.makeIterator(a),c=d.next();!c.done;c=d.next())e(c.value).callWhenSettled_(b,
h)})};g.all=function(a){var b=$jscomp.makeIterator(a),h=b.next();return h.done?e([]):new g(function(a,c){function d(b){return function(c){f[b]=c;n--;0==n&&a(f)}}var f=[],n=0;do f.push(void 0),n++,e(h.value).callWhenSettled_(d(f.length-1),c),h=b.next();while(!h.done)})};return g},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(e){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(e||"")+"_"+b++,e)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(e){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var e=a.next();$jscomp.generator.ensureIteratorResultIsObject_(e);if(e.done)this.yieldResult=e.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(e.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,e){e?this.finallyContexts_[e]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,e){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var g=f.value}catch(d){return this.context_.yieldAllIterator_=null,this.context_.throw_(d),this.nextStep_()}this.context_.yieldAllIterator_=null;e.call(this.context_,g);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function e(b){return a.throw(b)}return new Promise(function(f,g){function d(a){a.done?f(a.value):Promise.resolve(a.value).then(b,e).then(d,g)}d(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.findInternal=function(a,b,e){a instanceof String&&(a=String(a));for(var f=a.length,g=0;g<f;g++){var d=a[g];if(b.call(e,d,g,a))return{i:g,v:d}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,e){return $jscomp.findInternal(this,a,e).v}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,e){return a===e?0!==a||1/a===1/e:a!==a&&e!==e}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,e){var b=this;b instanceof String&&(b=String(b));var g=b.length;e=e||0;for(0>e&&(e=Math.max(e+g,0));e<g;e++){var d=b[e];if(d===a||Object.is(d,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,e){if(null==a)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,e){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,e||0)}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(e,f,g){return e==a&&"q"==f&&g==b}}));return!0===b.q}catch(e){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),d=Object.seal({}),c=new a([[b,2],[d,3]]);if(2!=c.get(b)||3!=c.get(d))return!1;c.delete(b);c.set(d,4);return!c.has(b)&&4==c.get(d)}catch(w){return!1}}function e(){}function f(a){if(!$jscomp.owns(a,d)){var b=new e;$jscomp.defineProperty(a,d,{value:b})}}function g(a){var b=Object[a];b&&(Object[a]=function(a){if(a instanceof e)return a;f(a);return b(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&
$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var d="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var p=0,k=function(a){this.id_=(p+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};k.prototype.set=function(a,b){f(a);if(!$jscomp.owns(a,d))throw Error("WeakMap key fail: "+a);a[d][this.id_]=b;return this};k.prototype.get=function(a){return $jscomp.owns(a,d)?a[d][this.id_]:void 0};k.prototype.has=
function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)};k.prototype.delete=function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)?delete a[d][this.id_]:!1};return k},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=d.get(b)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var c=d.entries(),e=c.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=c.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!c.next().done?!1:!0}catch(x){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbolIterator();var e=new WeakMap,f=function(a){this.data_={};this.head_=p();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};f.prototype.set=function(a,b){a=0===a?0:a;var c=g(this,a);c.list||(c.list=this.data_[c.id]=[]);c.entry?c.entry.value=b:(c.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:b},c.list.push(c.entry),this.head_.previous.next=c.entry,this.head_.previous=c.entry,this.size++);return this};f.prototype.delete=function(a){a=g(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};f.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=p();this.size=0};f.prototype.has=function(a){return!!g(this,a).entry};
f.prototype.get=function(a){return(a=g(this,a).entry)&&a.value};f.prototype.entries=function(){return d(this,function(a){return[a.key,a.value]})};f.prototype.keys=function(){return d(this,function(a){return a.key})};f.prototype.values=function(){return d(this,function(a){return a.value})};f.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};f.prototype[Symbol.iterator]=f.prototype.entries;var g=function(a,b){var c=b&&typeof b;"object"==
c||"function"==c?e.has(b)?c=e.get(b):(c=""+ ++k,e.set(b,c)):c="p_"+b;var d=a.data_[c];if(d&&$jscomp.owns(a.data_,c))for(a=0;a<d.length;a++){var f=d[a];if(b!==b&&f.key!==f.key||b===f.key)return{id:c,list:d,index:a,entry:f}}return{id:c,list:d,index:-1,entry:void 0}},d=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},p=function(){var a={};return a.previous=
a.next=a.head=a},k=0;return f},"es6","es3");
$jscomp.polyfill("Set",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),e=new a($jscomp.makeIterator([b]));if(!e.has(b)||1!=e.size||e.add(b)!=e||1!=e.size||e.add({x:4})!=e||2!=e.size)return!1;var d=e.entries(),p=d.next();if(p.done||p.value[0]!=b||p.value[1]!=b)return!1;p=d.next();return p.done||p.value[0]==b||4!=p.value[0].x||p.value[1]!=p.value[0]?!1:d.next().done}catch(k){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbolIterator();var e=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};e.prototype.add=function(a){a=0===a?0:a;this.map_.set(a,a);this.size=this.map_.size;return this};e.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};e.prototype.clear=function(){this.map_.clear();
this.size=0};e.prototype.has=function(a){return this.map_.has(a)};e.prototype.entries=function(){return this.map_.entries()};e.prototype.values=function(){return this.map_.values()};e.prototype.keys=e.prototype.values;e.prototype[Symbol.iterator]=e.prototype.values;e.prototype.forEach=function(a,b){var d=this;this.map_.forEach(function(e){return a.call(b,e,e,d)})};return e},"es6","es3");
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var b=[],f;for(f in a)$jscomp.owns(a,f)&&b.push(a[f]);return b}},"es8","es3");
(function(a){(a.SafeWeb=a.SafeWeb||{}).constants={SHASTA_URL:"https://ratings-wrs.norton.com",SHASTA_LOOKUP_PATH:"brief",DEFAULT_FULL_REPORT_URL:"https://safeweb.norton.com/report/show",HTTP_PROTOCOL:"http",HTTPS_PROTOCOL:"https",HTTPS_GET_METHOD:"GET",HTTPS_POST_METHOD:"POST",PII_SUBMISSION_TIMEOUT:2E3,SCAM_INSIGHT_BLOCK_PAGE_PATH:"content/ui/scam-insight-block-page.html",BLOCK_PAGE_PATH:"content/ui/blockedPage.html",SYMC_USER_AGENT:"X-Symc-User-Agent",WRS_HEADER_VALUES:{XBP_SAFEWEB:"xBP/SafeWeb",
XBP_SAFEWEB_YAHOO:"xBP/SafeWeb_Yahoo",XBP_SAFEWEB_YAHOO_ADVT:"xBP/SafeWeb_Yahoo_Advt"},ROOT_NODE:{TAG_NAME:"symantec",VERSION_ATTR:"v",CACHE_POSITIVE_ATTR:"cacheP",CACHE_NEGATIVE_ATTR:"cacheN"},PII_FLAGS:{EXIT_SITE:0,CONTINUE_TO_SITE:1,SUPPRESSED_DUE_TO_SILENTMODE:2,SUPPRESSED_DUE_TO_HTTPS:4},PII_SUBMISSION_STATUS:{SUCCESS:"Success",FAILURE:"Fail"},SITE_NODE:{TAG_NAME:"site",CANONICAL_SITE_ID_ATTR:"id",COMBINED_RATING_ATTR:"r",SECURITY_RATING_ATTR:"sr",BUSINESS_RATING_ATTR:"br",CACHE_ATTR:"cache",
PII_ENABLE_ATTR:"piien",PII_POLICY_HTTPS:"piipolhttps",PII_POLICY_ID:"piipolid",PII_POLICY_FIELD_TYPE:"piipolft"},WRS_RATINGS:{UNKNOWN_SITE:"u",BAD_SITE:"b",WARNING_SITE:"w",GOOD_SITE:"g",NORTON_SECURE_SITE:"r",PII_NOT_ENABLED:"n",PII_ENABLED:"y",PII_SILENCE:"s"},ANNOYANCE_FACTORS_KEYS:{PUAPP:!0,HRDUN:!0,JOKE:!0,MLAPP:!0,TRCKW:!0,TPSQT:!0,PPCNA:!0,HACK:!0,SPAM:!0,SWBPL:!0},PII_FACTORS_KEYS:{PIIAGE:"age",PIIPOP:"pop"},PII_POLICY_HTTPS_KEYS:{DONTCARE:"dc",HTTPS:"h"},IDENTITY_THREATS_KEYS:{MLWR:!0,MBCHG:!0,
RMTA:!0,PHISH:!0,BDOOR:!0,ISTLR:!0,DIAL:!0,DLDR:!0,SPWR:!0},SHOPPING_RISKS_KEYS:{CTFGS:!0,RCGS:!0,REPLC:!0},COMPUTER_THREATS_KEYS:{COHD:!0,ADWR:!0,VIRUS:!0,WORM:!0,SRISK:!0,BREXP:!0,MLWR:!0,MBCHG:!0,HEUR:!0,ELTMS:!0,TRJN:!0},SITE_FACT_NODE:{TAG_NAME:"d",REPORTED_BY_KEY:"reported_by",SRC_KEY:"src",ID_KEY:"id"},SITE_FACT_IDS:{PRIVACY_POLICY_APPROVED:"privacy policy approved",NETWORK_SCANNING_SERVICE:"network scanning service",SSL_CA_NAME:"ssl CA name",AUTHORIZED_RESELLER:"Authorized Reseller",CERTIFIED_BUSINESS:"certified business",
VERISIGN_TRUSTED:"VRTRU",VERISIGN_SSL:"VRSSL"},SITE_FACT_SOURCES:{SRC_BUYSAFE:"BUYSAFE",SRC_VERISIGN:"Verisign",SRC_MARK_MONITOR:"MARKMONITOR"},ATTRIBUTE_COUNT:"cnt",CACHE_LIMIT:1E3,RATING_TYPE:{WCID_HEURISTICS:1,WCID_CHECK_URL:2,SAFEWEB:3,SCAM_INSIGHT:4},MESSAGES:{WAX_FIELDS_FOUND:"45E6BAD1-9F79-4E16-BA3A-1F77AA21EAC9",PROCESS_PAGE_FOR_SCAM_FIELDS:"FEDA41BC-73DC-4F99-A2CF-B5589CF2D0F8",TOP_FRAME_UNLOADED:"E5C199FF-A74B-414F-803C-4C7030C0E573",CAN_ANALYZE_FOR_SCAM:"6E6CDFB7-4CF6-4C73-B998-6CA3432DDC07"},
IS_SCAM_INSIGHT_ENABLED:!0,performanceReporter:{COMPONENT:{SCAM_INSIGHT:"scam_insight"},TYPE:{INIT:"init",PII_PROTO_SUBMISSION:"_piiProtoSubmission",CALCULATE_SCAM_RATING:"_calculateScamInsightRating",HANDLE_PII_RATING:"_handlePIIEnabledRating",SET_WRS_RESPONSE:"setWrsResponse",HANDLE_MESSAGE:"_handleMessage",HANDLE_MESSAGE_CALLBACK:"_handleScamPageFoundCallback",HANDLE_CACHE_RESPONSE:"_handleCacheResponse",SEND_PII_SUBMISSION:"sendPIISubmission",COLLECT_PII_FIELDS:"_collectPIIFields",TOP_FRAME_UNLOADED:"topFrameUnloaded",
ADD_MUTATION_OBSERVER:"_addBodyMutationObserver",FIELD_FOUND_CALLBACK:"handleFieldsFoundCallback",WAX_CONTROLLER_INITIALIZE:"scamInsightWaxControllerInitialize",CAN_ANALYZE_HANDLER_RESPONSE:"canAnalyzeForScamHandlerResponse",RUN_WAX_ANALYSIS:"_runWaxAnalysis"}},SCAM_INSIGHT_RESULT:{UNTESTED:0,SUSPICIOUS_PAGE:1,SUSPICIOUS_NO_BLOCK_PAGE:2,NOT_SUSPICIOUS_PAGE:3},SCAM_INSIGHT_RATING_KEY:"scamRating",SCAM_ANALYSIS_STATE:{PENDING:0,ANALYZE:1},YAHOO_DOMAIN:"yahoo.com",HSPART_KEY:"hspart",HSPART_VALUE:["symantec",
"norton"]}})(executionContext);
(function(a){a.SafeWeb.telemetryWrapper=function(a,e){var b={},g=a.utils.isString,d=a.telemetryConstants;b.TELEMETRY_CATEGORY={SCAM_INSIGHT:"Scam_Insight"};b.actionType={PROTO:{PII_SUBMISSION:"PII_Submission"}};b.sendPIISubmissionStatusEvent=function(a){if(!g(a))return null;b.send(b.TELEMETRY_CATEGORY.SCAM_INSIGHT,b.actionType.PROTO.PII_SUBMISSION,a)};b.send=function(b,e,h){if(!g(b)||!g(e)||!g(h))return null;var f={};f[d.parameters.HIT_TYPE]=d.HIT_TYPE.EVENT;f[d.parameters.CATEGORY]=b;f[d.parameters.ACTION]=
e;f[d.parameters.LABEL]=h;(a.telemetry||a.telemetryProxy).send(f)};return b}(a.SymBfw,a.SafeWeb)})(executionContext);
(function(a){a.SafeWeb.Rating=function(a){var b=a.utils.isNil,f=a.utils.isArray,g=SafeWeb.constants,d=a.utils,p=a.localizer,k=a.utils.isInteger,h=a.utils.isString,n=SafeWeb.constants,c=function(d){if(b(d))throw Error("Input dictionary cannot be null");var e=c.ratingSchema,h;for(h in e){var f=e[h],g=d[h];if(b(g)){if(f.isRequired)throw Error("Cannot find value for key "+h+" in the input dictionary.");if(b(f.defaultValue))throw Error("Default value has not been supplied in the Schema.");this[h]=f.defaultValue}else{f=
f.typeChecker;if(!1===f(g))throw Error("Input value for key "+h+" does not match schema.");this[h]=g}}this.id=a.utils.createNewGuid()};c._checkPIISchema=function(a){return h(a.piiEnable)?n.WRS_RATINGS.PII_ENABLED!==a.piiEnable&&n.WRS_RATINGS.PII_SILENCE!==a.piiEnable?!0:h(a.piiPolHttps)&&h(a.piiPolID)&&f(a.piiFieldType)&&k(a.age)&&k(a.pop)?!0:!1:!1};c.ratingSchema={computerThreats:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},annoyanceFactors:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},
identityThreats:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},shoppingRisks:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},phishingThreats:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},siteRating:{isRequired:!0,typeChecker:d.isInteger},fullURL:{isRequired:!0,typeChecker:d.isString},normalizedURL:{isRequired:!0,typeChecker:d.isString},cacheTime:{isRequired:!1,typeChecker:d.isInteger,defaultValue:0},piiAttributes:{isRequired:!1,typeChecker:c._checkPIISchema,defaultValue:{piiEnable:n.WRS_RATINGS.PII_NOT_ENABLED}},
scamRating:{isRequired:!1,typeChecker:d.isInteger,defaultValue:g.SCAM_INSIGHT_RESULT.UNTESTED}};c.prototype.getComputerThreats=function(){return this.computerThreats};c.prototype.getAnnoyanceFactors=function(){return this.annoyanceFactors};c.prototype.getIdentityThreats=function(){return this.identityThreats};c.prototype.getShoppingRisks=function(){return this.shoppingRisks};c.prototype.getPhishingThreats=function(){return this.phishingThreats};c.prototype.getFullReportURL=function(){return g.DEFAULT_FULL_REPORT_URL+
"?url="+this.getFullURL()+"&ulang="+p.getLocale()};c.prototype.getSiteRating=function(){return this.siteRating};c.prototype.getFullURL=function(){return this.fullURL};c.prototype.getNormalizedURL=function(){return this.normalizedURL};c.prototype.getID=function(){return this.id};c.prototype.getCacheTime=function(){return this.cacheTime};c.prototype.getPIIEnValue=function(){return this.piiAttributes.piiEnable};c.prototype.getPIIPolID=function(){return b(this.piiAttributes.piiPolID)?null:this.piiAttributes.piiPolID};
c.prototype.getPIIHTTPS=function(){return b(this.piiAttributes.piiPolHttps)?null:this.piiAttributes.piiPolHttps};c.prototype.getPIIFieldType=function(){return b(this.piiAttributes.piiFieldType)?[]:this.piiAttributes.piiFieldType};c.prototype.getPIIAge=function(){return b(this.piiAttributes.age)?0:this.piiAttributes.age};c.prototype.getPIIPop=function(){return b(this.piiAttributes.pop)?0:this.piiAttributes.pop};c.prototype.getScamRating=function(){return this.scamRating};c.prototype.serialize=function(){return JSON.stringify(this)};
c.SITE_RATING={SW_INVALID_STATE:0,SW_TRUSTED_STATE:1,SW_NEUTRAL_STATE:2,SW_KNOWN_PHISHING_STATE:3,SW_SUSPECTED_PHISHING_STATE:4,SW_KNOWN_MALICIOUS_STATE:5,SW_CAUTION_MALICIOUS_STATE:6,SW_NORTON_CERTIFIED:7,SW_TRUSTED_TRANSACTION_STATE:8,SW_UNTRUSTED_TRANSACTION_STATE:9,SW_PAGE_BAD_UNTRUSTED_TRANSACTION_STATE:10,SW_DISABLED_STATE:11,SW_UNLICENSED_STATE:12,SW_ERROR_STATE:13,SW_PENDING_STATE:14,SW_MAX_STATE:15};return c}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.WrsParser=function(a){var b=a.utils.isNil,f=a.utils.isntNil,g=a.utils.isEmptyObject,d=SafeWeb.constants,p=a.logger,k=SafeWeb.Rating;a=function(){this._rootDict={cacheP:600,cacheN:600}};a.prototype.parseWRSResponse=function(a,d){if(b(a))return null;if(b(d))throw Error("URL Array cannot be null.");a=$(a);a=this.parseRootNode(a);return b(a)?null:this.parseSiteInformation(a,d)};a.prototype.parseSiteInformation=function(a,e){a=a.find(d.SITE_NODE.TAG_NAME);var c=a.length;if(0===c)return null;
if(e.length!==c)return p.error("Lengths of input URL Array("+e.length+") and Shasta results("+c+") do not match."),null;for(var f=[],h=0;h<c;h++){var n=a[h],u=n.attributes,v=u.length,m={},t=!1,l={};m.fullURL=e[h];var q=0;for(q=0;q<v;q++){var r=u.item(q);switch(r.nodeName){case d.SITE_NODE.CANONICAL_SITE_ID_ATTR:m.normalizedURL=r.value;break;case d.SITE_NODE.COMBINED_RATING_ATTR:m.combinedRating=r.value;break;case d.SITE_NODE.SECURITY_RATING_ATTR:m.securityRating=r.value;t=!0;break;case d.SITE_NODE.BUSINESS_RATING_ATTR:m.shoppingRating=
r.value;break;case d.SITE_NODE.CACHE_ATTR:m.cacheTime=Number(r.value);break;case d.SITE_NODE.PII_ENABLE_ATTR:l.piiEnable=r.value;break;case d.SITE_NODE.PII_POLICY_HTTPS:l.piiPolHttps=r.value;break;case d.SITE_NODE.PII_POLICY_ID:l.piiPolID=r.value;break;case d.SITE_NODE.PII_POLICY_FIELD_TYPE:r=r.value,"*"===r?l.piiFieldType=["*"]:(r=r.split(",").map(Number),l.piiFieldType=r.filter(function(a){return!isNaN(a)}))}}m.piiAttributes=l;g(m.piiAttributes)&&(m.piiAttributes.piiEnable=d.WRS_RATINGS.PII_NOT_ENABLED);
b(m.normalizedURL)&&(m.normalizedURL="");b(m.combinedRating)&&(m.combinedRating=d.WRS_RATINGS.UNKNOWN_SITE);b(m.securityRating)&&(m.securityRating=d.WRS_RATINGS.UNKNOWN_SITE);b(m.shoppingRating)&&(m.shoppingRating=d.WRS_RATINGS.UNKNOWN_SITE);b(m.cacheTime)&&(m.cacheTime=!1===t?this._rootDict.cacheN:this._rootDict.cacheP);m.siteRating=this.getSiteRating(m.securityRating,m.shoppingRating);this.parseSiteAttributes($(n),m);n=new k(m);f.push(n)}return f};a.prototype.parseSiteAttributes=function(a,e){a=
a.children();for(var c=a.length,h=0,g=0,k=0,n=0,p=0;p<c;p++){var m=a.get(p),t=m.nodeName;m=m.attributes;f(d.ANNOYANCE_FACTORS_KEYS[t])&&(g+=Number(m[d.ATTRIBUTE_COUNT].value));f(d.IDENTITY_THREATS_KEYS[t])&&(k+=Number(m[d.ATTRIBUTE_COUNT].value));f(d.SHOPPING_RISKS_KEYS[t])&&(n+=Number(m[d.ATTRIBUTE_COUNT].value));f(d.COMPUTER_THREATS_KEYS[t])&&(h+=Number(m[d.ATTRIBUTE_COUNT].value));f(d.PII_FACTORS_KEYS[t])&&(b(e.piiAttributes)&&(e.piiAttributes={}),e.piiAttributes[d.PII_FACTORS_KEYS[t]]=Number(m[d.PII_FACTORS_KEYS[t]].value))}e.computerThreats=
h;e.annoyanceFactors=g;e.identityThreats=k;e.shoppingRisks=n};a.prototype.getSiteRating=function(a,b){if(a===d.WRS_RATINGS.NORTON_SECURE_SITE)return k.SITE_RATING.SW_NORTON_CERTIFIED;if(a===d.WRS_RATINGS.GOOD_SITE){if(b===d.WRS_RATINGS.GOOD_SITE)return k.SITE_RATING.SW_TRUSTED_TRANSACTION_STATE;if(b===d.WRS_RATINGS.UNKNOWN_SITE)return k.SITE_RATING.SW_TRUSTED_STATE}return a===d.WRS_RATINGS.BAD_SITE?b===d.WRS_RATINGS.BAD_SITE?k.SITE_RATING.SW_PAGE_BAD_UNTRUSTED_TRANSACTION_STATE:k.SITE_RATING.SW_KNOWN_MALICIOUS_STATE:
b===d.WRS_RATINGS.WARNING_SITE||b===d.WRS_RATINGS.BAD_SITE?k.SITE_RATING.SW_UNTRUSTED_TRANSACTION_STATE:a===d.WRS_RATINGS.WARNING_SITE?k.SITE_RATING.SW_CAUTION_MALICIOUS_STATE:k.SITE_RATING.SW_NEUTRAL_STATE};a.prototype.parseRootNode=function(a){a=a.find(d.ROOT_NODE.TAG_NAME);if(0===a.length)return null;for(var b=a[0].attributes,c=b.length,e=0;e<c;e++){var f=b.item(e);switch(f.nodeName){case d.ROOT_NODE.VERSION_ATTR:this._rootDict[d.ROOT_NODE.VERSION_ATTR]=f.value;break;case d.ROOT_NODE.CACHE_POSITIVE_ATTR:this._rootDict[d.ROOT_NODE.CACHE_POSITIVE_ATTR]=
Number(f.value);break;case d.ROOT_NODE.CACHE_NEGATIVE_ATTR:this._rootDict[d.ROOT_NODE.CACHE_NEGATIVE_ATTR]=Number(f.value)}}return a};return a}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.connection=function(a){var b={},f=a.utils.isNil,g=a.utils.isntNil,d=a.utils.isFunction,p=a.utils.isArray,k=SafeWeb.constants,h=SafeWeb.WrsParser,n=a.logger;b.getResultForURL=function(a,e){if(f(a))throw Error("URL cannot be null");if(!1===d(e))throw Error("Shasta Connection callback cannot be null");var c=encodeURIComponent(SafeWeb.cache.safeURL(a));c=k.SHASTA_URL+"/"+k.SHASTA_LOOKUP_PATH+"?url="+c;var g=b.constructHeader({senderURL:a,methodType:k.HTTPS_GET_METHOD});b.shastaConnection(c,
k.HTTPS_GET_METHOD,function(b){var c=b.status,d=b.responseXML;if(200===c){var f=(new h).parseWRSResponse(d,[a]);SafeWeb.cache.addRatingsToCache(f);setTimeout(function(){e(c,f)},1)}else setTimeout(function(){e(c,b)},1)},g)};b.constructHeader=function(a){var b={};if(g(a))switch(a.methodType){case k.HTTPS_GET_METHOD:b[k.SYMC_USER_AGENT]=k.WRS_HEADER_VALUES.XBP_SAFEWEB;break;case k.HTTPS_POST_METHOD:if(g(a.senderURL)){var c=new URI(a.senderURL),d=c.domain();c=c.query(!0);g(c)&&d===k.YAHOO_DOMAIN&&k.HSPART_VALUE.includes(c[k.HSPART_KEY])&&
(f(a.bAdvtFlag)?b[k.SYMC_USER_AGENT]=k.WRS_HEADER_VALUES.XBP_SAFEWEB_YAHOO:b[k.SYMC_USER_AGENT]=k.WRS_HEADER_VALUES.XBP_SAFEWEB_YAHOO_ADVT)}break;default:b[k.SYMC_USER_AGENT]=k.WRS_HEADER_VALUES.XBP_SAFEWEB}return new Headers(b)};b.getResultsForURLs=function(a,e,g){if(!1===p(a))throw Error("URL Array cannot be null");if(0===a.length)throw Error("URL Array length cannot be null");if(!1===d(e))throw Error("Shasta Connection callback cannot be null");if(f(g))throw Error("Payload cannot null");var c=
k.SHASTA_URL+"/"+k.SHASTA_LOOKUP_PATH,x="",n;for(n in a)x+=a[n]+"\r\n";g.methodType=k.HTTPS_POST_METHOD;g=b.constructHeader(g);b.shastaConnection(c,k.HTTPS_POST_METHOD,function(b){var c=b.status,d=b.responseXML;if(200===c){var q=(new h).parseWRSResponse(d,a);SafeWeb.cache.addRatingsToCache(q);setTimeout(function(){e(c,q)},1)}else setTimeout(function(){e(c,b)},1)},g,x)};b.shastaConnection=function(b,e,g,h,k){var c,m,p,l;return $jscomp.asyncExecutePromiseGeneratorProgram(function(q){switch(q.nextAddress){case 1:if(f(b))throw Error("API URL cannot be null");
if(f(e))throw Error("HTTP Method cannot be null");if(!1===d(g))throw Error("Shasta Callback cannot be null");q.setCatchFinallyBlocks(2);return q.yield(a.utils.safeFetch(b,{credentials:"omit",method:e,headers:h,body:k}),4);case 4:c=q.yieldResult;if(!0!==c.ok){n.debug("safeFetch() FAILED - url : "+c.url+" - HTTP code : "+c.status);g({status:c.status,responseXML:null});q.jumpTo(5);break}return q.yield(c.text(),6);case 6:m=q.yieldResult,p=(new DOMParser).parseFromString(m,"text/xml"),g({status:c.status,
responseXML:p});case 5:q.leaveTryBlock(0);break;case 2:l=q.enterCatchBlock(),n.error("Exception received from safeFetch \n"+l),g({status:null,responseXML:null}),q.jumpToEnd()}})};return b}(a.SymBfw)})(executionContext);
(function(a){a=a.SafeWeb.ScamInsightPII=a.SafeWeb.ScamInsightPII||{};var b=dcodeIO.ProtoBuf.newBuilder({})["import"]({"package":"PIIFeatureTelem",syntax:"proto2",options:{optimize_for:"LITE_RUNTIME"},messages:[{name:"ScamInsight_PII_Submission_List",syntax:"proto2",fields:[{rule:"optional",type:"uint32",name:"Version",id:1,options:{"default":1}},{rule:"optional",type:"bytes",name:"Enterprise_GUID",id:2},{rule:"optional",type:"bytes",name:"Machine_GUID",id:3},{rule:"optional",type:"bytes",name:"Machine_CAT",
id:4},{rule:"optional",type:"string",name:"ProductName",id:5,options:{"default":""}},{rule:"optional",type:"string",name:"ProductVersion",id:6,options:{"default":""}},{rule:"repeated",type:"Submission_Type",name:"Submission",id:7}],messages:[{name:"Submission_Type",syntax:"proto2",fields:[{rule:"optional",type:"int64",name:"UTCTime",id:1},{rule:"optional",type:"sint32",name:"LocalTZUTCOffset",id:2},{rule:"optional",type:"string",name:"Site_URL",id:3},{rule:"optional",type:"string",name:"Referrer_URL",
id:4},{rule:"optional",type:"string",name:"FormAction_URL",id:5},{rule:"optional",type:"string",name:"PII_PolicyID",id:6},{rule:"repeated",type:"uint32",name:"Form_Fields",id:7},{rule:"optional",type:"uint32",name:"PII_Flags",id:8}]}]}],enums:[{name:"ScamInsight_PII_FlagValues",syntax:"proto2",values:[{name:"SCAMINSIGHT_PII_CONTINUED_TO_PAGE",id:1},{name:"SCAMINSIGHT_PII_SUPPRESSEDDUETOSILENTMODE",id:2},{name:"SCAMINSIGHT_PII_SUPPRESSEDDUETOHTTPS",id:4}]}],isNamespace:!0}).build();a.proto=b})(executionContext);
(function(a){a.SafeWeb.piiprotoutils=function(a){var b={},f=SafeWeb.ScamInsightPII.proto.PIIFeatureTelem.ScamInsight_PII_Submission_List,g=f.Submission_Type,d=a.utils.isNil,p=a.utils.isArray,k=a.utils.isEmptyObject,h=a.utils.isString,n=a.utils.urlWithoutQueryParameters,c="1.0.0",w=function(){this.piiSubmissionItem={UNIX_TIME:null,OFFSET_TIME:null,SITE_URL:null,REFERRER_URL:null,FORM_ACTION_URL:null,PII_POLICYID:null,FORM_FIELDS:null,PII_FLAGS:null}};w.prototype.setSubmissionTime=function(){var a=
new Date;this.piiSubmissionItem.UNIX_TIME=a.getTime();this.piiSubmissionItem.OFFSET_TIME=a.getTimezoneOffset()};w.prototype.setSiteUrl=function(a){a=n(a);a=encodeURIComponent(a);this.piiSubmissionItem.SITE_URL=a};w.prototype.isValidPIISubmissionData=function(){return d(this.piiSubmissionItem.UNIX_TIME)||d(this.piiSubmissionItem.OFFSET_TIME)||k(this.piiSubmissionItem.SITE_URL)||!h(this.piiSubmissionItem.SITE_URL)||k(this.piiSubmissionItem.PII_POLICYID)||!h(this.piiSubmissionItem.PII_POLICYID)||!p(this.piiSubmissionItem.FORM_FIELDS)||
d(this.piiSubmissionItem.PII_FLAGS)?!1:!0};b._fillPIIItem=function(a,b){k(a.piiSubmissionItem.REFERRER_URL)||b.setReferrerURL(encodeURIComponent(a.piiSubmissionItem.REFERRER_URL));k(a.piiSubmissionItem.FORM_ACTION_URL)||b.setFormActionURL(encodeURIComponent(a.piiSubmissionItem.FORM_ACTION_URL));var c=dcodeIO.Long.fromNumber(a.piiSubmissionItem.UNIX_TIME);b.setUTCTime(c);b.setLocalTZUTCOffset(a.piiSubmissionItem.OFFSET_TIME);b.setSiteURL(a.piiSubmissionItem.SITE_URL);b.setPIIPolicyID(a.piiSubmissionItem.PII_POLICYID);
b.setFormFields(a.piiSubmissionItem.FORM_FIELDS);b.setPIIFlags(a.piiSubmissionItem.PII_FLAGS)};b.setPIIProductVersion=function(a){if(!h(a))throw Error("Invalid string");c=a};b._createPIIList=function(a){var d=new f,e=new g;d.setVersion(1);d.setProductName("NSSS");d.setProductVersion(c);b._fillPIIItem(a,e);d.setSubmission(e);return d};b.submitShastaPII=function(a){var c,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress){if(!(a instanceof w))throw Error("Invalid PII Object");
if(!a.isValidPIISubmissionData())throw Error("Invalid PII Submission Data");c=b._createPIIList(a);if(d(c))throw Error("PII Creation Failed");e=c.toArrayBuffer();if(d(e))throw Error("Invalid Serialized Message");return f.yield(b._sendPIIDataToShasta(e),2)}return f.return(f.yieldResult)})};b._sendPIIDataToShasta=function(b){var c,d,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress)return c={"Content-Type":"application/x-protobuf"},d={method:"POST",headers:c,body:b},
f.setCatchFinallyBlocks(2),f.yield(fetch("https://shasta-clt.norton.com/incident-pii/1",d),4);if(2!=f.nextAddress){e=f.yieldResult;if(e.status!==a.constants.httpStatusCodes.OK)throw Error("PII Submission Failed");return f.return()}f.enterCatchBlock();throw Error("PII Submission Failed");})};b.getPIISUbmissionObj=function(){return new w};return b}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.cache=function(b){var e=b.utils.isNil,f=b.utils.isntNil,g=b.utils.isEmptyObject,d=b.logger,p=SafeWeb.constants,k=SafeWeb.connection,h={_normalizedURLToRatingsMap:{},_cachedURLs:0,safeURL:function(a){a=new URI(a);return a.protocol()+"://"+a.hostname()+a.pathname()},addRatingsToCache:function(a){if(e(a)||0===a.length)throw Error("Ratings array cannot be null or empty");var b=function(a,b){setTimeout(function(){h.removeRatingFromCache(a)},b)},f;for(f in a){if(h._cachedURLs>=p.CACHE_LIMIT)break;
var g=a[f];if(!e(g)){var k=g.getCacheTime();if(0!==k){var n=g.getNormalizedURL(),v=null;e(n)||0===n.length?(v=h.safeURL(g.getFullURL()),d.error("Normalized URL cannot not be null or empty:"+v)):(e(h._normalizedURLToRatingsMap[n])?h._cachedURLs++:v=h.safeURL(g.getFullURL()),h._normalizedURLToRatingsMap[n]=g,b(n,1E3*k))}}}},removeRatingFromCache:function(a){if(e(a))throw Error("Normalized URL cannot be null");delete h._normalizedURLToRatingsMap[a];h._cachedURLs--},getRatingForURL:function(a,b){var c=
h.ratingForCachedURL(a);f(c)?setTimeout(function(){b(c)},1):k.getResultForURL(a,function(a,c){var d=200===a?c[0]:null;setTimeout(function(){b(d)},1)})},ratingForCachedURL:function(b){if(g(h._normalizedURLToRatingsMap))return null;var c=new URI(b);do{var d=c.hostname(),e=c.domain();var k=c.segment();var p=c.pathname(),n=k.length,m=0;do{k=d+p;k=h._normalizedURLToRatingsMap[k];if(f(k))break;p=p.slice(0,p.lastIndexOf("/"));m++}while(m<n);if(!f(k)){if(!0===c.is("IP")&&(k=h._normalizedURLToRatingsMap[d],
f(k)))break;d=c.subdomain();if(f(d)&&0<d.length){p=d.split(".").length;n=0;do{k=d+"."+e;k=h._normalizedURLToRatingsMap[k];if(f(k))break;d=d.slice(d.indexOf(".")+1,d.length);n++}while(n<p);if(f(k))break}k=e;k=h._normalizedURLToRatingsMap[k]}}while(0);c=null;f(k)&&(c=JSON.parse(JSON.stringify(k)),c.fullURL=b,c=new a.SafeWeb.Rating(c));return c},getRatingsForURLs:function(a,b,d){var c=[];c.length=a.length;var g={},p=[],n;for(n in a){var m=a[n];if(e(m))c[n]=null;else{var t=h.ratingForCachedURL(m);f(t)?
c[n]=t:(g[p.length]=n,p.push(m))}}0===p.length?setTimeout(function(){b(c)},1):k.getResultsForURLs(p,function(a,d){if(200===a)for(var e in d)c[g[e]]=d[e];setTimeout(function(){b(c)},1)},d)},updateCacheRatingsForUrl:function(a){if(!e(a)){var b=a.getNormalizedURL();e(b)||0===b.length?d.log("Normalized url for this newRating is null, dont proceed further to alter in this case"):f(h._normalizedURLToRatingsMap[b])&&(h._normalizedURLToRatingsMap[b]=a)}}};return h}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.manager=function(a){var b=SafeWeb.cache,f=a.utils.isNil,g=a.utils.isFunction,d={getRatingForURL:function(a,e){if(f(a))throw Error("URL array cannot be null or empty.");if(!1===g(e))throw Error("Callback function cannot be null.");!1===d.validateURL(a)?setTimeout(function(){e(null)},1):b.getRatingForURL(a,e)},getRatingsForURLs:function(a,e,h){if(f(a)||0===a.length)throw Error("URL array cannot be null or empty.");if(!1===g(e))throw Error("Callback function cannot be null.");
for(var k in a)!1===d.validateURL(a[k])&&(a[k]=null);b.getRatingsForURLs(a,e,h)},validateURL:function(a){if(f(a))return!1;var b=new URI(a);a=b.protocol();b=b.hostname();return 0===a.length||0===b.length?!1:"http"===a||"https"===a?!0:!1}};return d}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.scamInsightUtility=function(a,e){var b=a.utils.urlWithoutQueryParameters,g=a.utils.isEmptyObject,d={};d._viewAnywayCache=new Set;d.addToViewAnywayCache=function(a){g(a)||(a=b(a),d._viewAnywayCache.has(a)||(d._viewAnywayCache.add(a),setTimeout(d._removeFromViewCache,18E5,a)))};d._removeFromViewCache=function(b){a.logger.debug("Removing from view cache : "+b);d._viewAnywayCache.delete(b)};d.isURLInViewAnywayCache=function(a){if(g(a))return!1;a=b(a);return d._viewAnywayCache.has(a)};
return d}(a.SymBfw,a.SafeWeb)})(executionContext);
(function(a){a.SafeWeb.scamInsightMgr=function(a,e){var b=a.extensionAdapter,g=a.utils.isEmptyObject,d=a.utils.isNil,p=a.utils.isntNil,k=a.utils.isArray,h=a.utils.isInteger,n=a.utils.isString,c=e.constants,w=a.telemetrySettings,x=e.piiprotoutils,y=a.utils.urlProtocol,u=a.logger,v=a.utils.isFunction,m=a.performanceReporterFactory,t=e.piiprotoutils,l={initialize:function(){if(c.IS_SCAM_INSIGHT_ENABLED){var a=c.performanceReporter.TYPE.INIT+":"+Date.now();m.reportStartForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,
a);l._processedTabFields=new Map;l._PIISubmissionInfo=new Map;l._scamPageFoundCallback=null;b.addMessageListener(l._handleMessage);b.addTabRemovedEventListener(l._handleTabClose);m.reportStopForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,a)}},registerEventCallback:function(a){if(!v(a))throw Error("Invalid Callback function");l._scamPageFoundCallback=a},setVersion:function(a){if(!n(a))throw Error("Invalid string");t.setPIIProductVersion(a)},_getSITabInfo:function(a){var b=l._processedTabFields.get(a);
d(b)&&(b=new Map,b.set("waxFieldsInfo",new Set),b.set("wrsScamResponse",{}),b.set("matchedFields",new Set),b.set("piiSubmissionTimer",0),b.set("piiFlag",0),b.set("piiSubmitted",!1),b.set("scamInsightBlockPageHandled",!1),l._processedTabFields.set(a,b));return b},_collectPIIFields:function(a,b){if(h(a)&&k(b)&&!(0>=b.length)){var d=c.performanceReporter.TYPE.COLLECT_PII_FIELDS+":"+Date.now();m.reportStartForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,d);var e=l._getSITabInfo(a),f=e.get("waxFieldsInfo"),
g=f.size;b.every(function(a){return f.add(a)});var r=f.size;l._processedTabFields.set(a,e);u.debug("Received WAX fields for tabID : "+a+" arrPIIFields : "+b);u.debug("Processed Tab fields map after wax update : "+a);u.debug(l._processedTabFields.get(a));r>g&&l._calculateScamInsightRating(a);m.reportStopForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,d)}},_getMatchedFields:function(a,b){return d(b)||0===b.size||d(a)||0===a.size?new Set:a.has("*")?b:new Set([].concat($jscomp.arrayFromIterable(a)).filter(function(a){return b.has(a)}))},
_piiProtoSubmission:function(a,b,f){if(!w.isTelemetryEnabled())return null;var h=x.getPIISUbmissionObj();if(g(h)||d(f)||0===f.size)return null;var r=c.performanceReporter.TYPE.PII_PROTO_SUBMISSION+":"+Date.now();m.reportStartForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,r);var q=a.getFullURL();a=a.getPIIPolID();h.setSiteUrl(q);h.setSubmissionTime();h.piiSubmissionItem.PII_FLAGS=b;h.piiSubmissionItem.PII_POLICYID=a;h.piiSubmissionItem.FORM_FIELDS=[].concat($jscomp.arrayFromIterable(f));
x.submitShastaPII(h).then(function(a){u.debug("Protobuf submission successful");e.telemetryWrapper.sendPIISubmissionStatusEvent(c.PII_SUBMISSION_STATUS.SUCCESS)}).catch(function(a){u.debug("Protobuf submission failed - "+a);e.telemetryWrapper.sendPIISubmissionStatusEvent(c.PII_SUBMISSION_STATUS.FAILURE)});m.reportStopForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,r)},getBlockPageData:function(a){if(!h(a))return null;var b=l._PIISubmissionInfo.get(a);if(d(b))return null;var e={},f=b.get("wrsScamResponse");
b.get("piiSubmitted")||(l.sendPIISubmission(c.PII_FLAGS.EXIT_SITE,a),b.set("piiSubmitted",!0),l._PIISubmissionInfo.set(a,b));e.url=f.getFullURL();e.ageScore=f.getPIIAge();e.prevalenceScore=f.getPIIPop();return e},sendPIISubmission:function(a,b){if(!h(b)||!h(a)||-1===Object.values(c.PII_FLAGS).indexOf(a))return null;var e=l._PIISubmissionInfo.get(b);if(d(e))return null;b=c.performanceReporter.TYPE.SEND_PII_SUBMISSION+":"+Date.now();m.reportStartForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,
b);var f=e.get("wrsScamResponse");e=e.get("matchedFields");l._piiProtoSubmission(f,a,e);m.reportStopForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,b)},_sendPIISubmissionSilentRating:function(a){if(!h(a))return null;var b=l._processedTabFields.get(a);if(d(b))return null;var c=b.get("wrsScamResponse"),e=b.get("matchedFields"),f=b.get("piiFlag");l._piiProtoSubmission(c,f,e);b.set("piiSubmitted",!0);l._processedTabFields.set(a,b)},_sendPIISubmissionSilentRatingOnTabClose:function(a){if(!h(a))return null;
var b=l._processedTabFields.get(a);if(d(b))return null;if(!b.get("piiSubmitted")){a=b.get("wrsScamResponse");var c=b.get("piiFlag"),e=b.get("matchedFields");b=b.get("piiSubmissionTimer");l._piiProtoSubmission(a,c,e);clearTimeout(b)}},_calculateScamInsightRating:function(a){if(!h(a))return null;var b=l._processedTabFields.get(a);if(d(b))return null;var e=b.get("waxFieldsInfo"),f=b.get("wrsScamResponse");if(d(e)||0===e.size||g(f))return null;e=[c.SCAM_INSIGHT_RESULT.SUSPICIOUS_PAGE,c.SCAM_INSIGHT_RESULT.SUSPICIOUS_NO_BLOCK_PAGE];
var k=f.getScamRating();if(d(k))throw Error("ScamInsight rating cannot be null");var q=c.performanceReporter.TYPE.CALCULATE_SCAM_RATING+":"+Date.now();m.reportStartForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,q);if(e.includes(k))l._handleCacheResponse(a,f),u.debug("Handled scam rating from cache for tabId : "+a);else{switch(f.getPIIEnValue()){case c.WRS_RATINGS.PII_ENABLED:case c.WRS_RATINGS.PII_SILENCE:l._handlePIIEnabledRating(a,b)}m.reportStopForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,
q)}},_handlePIIEnabledRating:function(a,b){var e=c.performanceReporter.TYPE.HANDLE_PII_RATING+":"+Date.now();m.reportStartForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,e);var f=b.get("waxFieldsInfo"),g=b.get("wrsScamResponse"),h=g.getPIIEnValue(),k=new Set(g.getPIIFieldType());if(d(k)||0===k.size)return null;f=l._getMatchedFields(k,f);if(d(f)||0===f.size)return l._updateCachedScamRating(g,c.SCAM_INSIGHT_RESULT.NOT_SUSPICIOUS_PAGE),null;b.set("matchedFields",f);l._processedTabFields.set(a,
b);u.debug("Processed Tab fields map after matched fields update : "+a);u.debug(l._processedTabFields.get(a));f=g.getPIIHTTPS();d(f)&&(f=c.PII_POLICY_HTTPS_KEYS.DONTCARE);var q=g.getFullURL();k=y(q);d(k)&&(k=c.HTTP_PROTOCOL);h===c.WRS_RATINGS.PII_ENABLED&&f===c.PII_POLICY_HTTPS_KEYS.DONTCARE||h===c.WRS_RATINGS.PII_ENABLED&&f===c.PII_POLICY_HTTPS_KEYS.HTTPS&&k===c.HTTP_PROTOCOL?(l._handleScamPageFoundCallback(a,q),l._updateCachedScamRating(g,c.SCAM_INSIGHT_RESULT.SUSPICIOUS_PAGE)):(q=0,h===c.WRS_RATINGS.PII_ENABLED&&
f===c.PII_POLICY_HTTPS_KEYS.HTTPS&&k===c.HTTPS_PROTOCOL&&(q=c.PII_FLAGS.SUPPRESSED_DUE_TO_HTTPS),h===c.WRS_RATINGS.PII_SILENCE&&(q=c.PII_FLAGS.SUPPRESSED_DUE_TO_SILENTMODE),b.get("piiSubmissionTimer")||(h=setTimeout(l._sendPIISubmissionSilentRating,c.PII_SUBMISSION_TIMEOUT,a),b.set("piiFlag",q),b.set("piiSubmissionTimer",h),l._processedTabFields.set(a,b)),l._updateCachedScamRating(g,c.SCAM_INSIGHT_RESULT.SUSPICIOUS_NO_BLOCK_PAGE));m.reportStopForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,
e)},setWrsResponse:function(a,e){var f=c.performanceReporter.TYPE.SET_WRS_RESPONSE+":"+Date.now();m.reportStartForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,f);if(!d(a)&&!g(e)){u.debug("WRS response set. TabId : "+a+" url : "+e.fullURL);var h=l._getSITabInfo(a);h.set("wrsScamResponse",e);e=e.getPIIEnValue();e!==c.WRS_RATINGS.PII_ENABLED&&e!==c.WRS_RATINGS.PII_SILENCE||b.getTab(a,function(a){b.sendMessageToTab(a,{id:c.MESSAGES.PROCESS_PAGE_FOR_SCAM_FIELDS,state:c.SCAM_ANALYSIS_STATE.ANALYZE})});
l._processedTabFields.set(a,h);l._calculateScamInsightRating(a);m.reportStopForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,f)}},deletePIISubmissionInfo:function(a){if(!h(a))return null;var b=l._PIISubmissionInfo.get(a);if(d(b))return null;l._PIISubmissionInfo.delete(a)},_handleTabClose:function(a){if(!h(a))return null;l.deletePIISubmissionInfo(a)},_handleMessage:function(a,e,f){if(!d(a)&&!d(a.id))switch(f=b.getTabID(f),a.id){case c.MESSAGES.WAX_FIELDS_FOUND:if(d(a.data))break;e=a.data;
if(0>=e.length)break;l._collectPIIFields(f,e);break;case c.MESSAGES.TOP_FRAME_UNLOADED:e=c.performanceReporter.TYPE.TOP_FRAME_UNLOADED+":"+Date.now();m.reportStartForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,e);a=l._processedTabFields.get(f);if(d(a))break;a.get("piiSubmissionTimer")&&l._sendPIISubmissionSilentRatingOnTabClose(f);l._processedTabFields.delete(f);m.reportStopForComponent(c.performanceReporter.COMPONENT.SCAM_INSIGHT,e);break;case c.MESSAGES.CAN_ANALYZE_FOR_SCAM:f=l._processedTabFields.get(f),
d(f)||(f=f.get("wrsScamResponse"),d(f)||(f=f.getPIIEnValue(),f!==c.WRS_RATINGS.PII_ENABLED&&f!==c.WRS_RATINGS.PII_SILENCE||e(c.SCAM_ANALYSIS_STATE.ANALYZE)))}},_handleScamPageFoundCallback:function(a,b){if(h(a)&&!e.scamInsightUtility.isURLInViewAnywayCache(b)&&(b=l._processedTabFields.get(a),!d(b))){var c=b.get("scamInsightBlockPageHandled");if(!p(c)||!0!==c){c=b.get("matchedFields");var f=b.get("wrsScamResponse");u.debug("Scam Page detected : ");u.debug(b);l._scamPageFoundCallback(a);var g=new Map;
g.set("wrsScamResponse",f);g.set("matchedFields",c);g.set("piiSubmitted",!1);l._PIISubmissionInfo.set(a,g);b.set("scamInsightBlockPageHandled",!0);l._processedTabFields.set(a,b)}}},_handleCacheResponse:function(a,b){h(a)&&!d(b)&&b.getScamRating()===c.SCAM_INSIGHT_RESULT.SUSPICIOUS_PAGE&&v(l._scamPageFoundCallback)&&l._handleScamPageFoundCallback(a,b.getFullURL())},_updateCachedScamRating:function(a,b){!d(a)&&h(b)&&(a=e.cache.ratingForCachedURL(a.getFullURL()),d(a)||a.getScamRating()===b||(a[c.SCAM_INSIGHT_RATING_KEY]=
b,e.cache.updateCacheRatingsForUrl(a)))}};l.initialize();return l}(a.SymBfw,a.SafeWeb)})(executionContext);
