var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(a,d,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,b,c){if(d){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var f=a[c];f in b||(b[f]={});b=b[f]}a=a[a.length-1];c=b[a];d=d(c);d!=c&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,b){var c=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var d=c.length,g=a.length;b=Math.max(0,Math.min(b|0,c.length));for(var e=0;e<g&&b<d;)if(c[b++]!=a[e++])return!1;return e>=g}},"es6","es3");
(function(a){a.NSSS.sb_ask=function(a){var b=a.utils.isntNil,c={initialize:function(){c.parsePage=function(){if(b(Utils)){if(window.location.href.startsWith("http://jp.ask.com"))Utils.execTopBtmSponsQuery("//div[@class='ovbox']/a[not(@class)]/span[@class='l']","//div[@class='ovbox']/a[not(@class)]/span[last()]");else{var a=document.getElementById("sponsoredRight"),c=document.getElementById("midRail"),e=document.getElementById("rr_sa");Utils.execTopBtmSponsQuery("//div[@id='adBlock']/div[contains(@class,'c_')]/div[position()=1]/a",
"//div[@id='adBlock']/div[contains(@class,'c_')]/div[position()=2]/a");Utils.execTopBtmSponsQuery("//div[contains(@class,'adStd')]/a[contains(@class,'titleLink') or contains(@class,'test_titleLink')]","//div[contains(@class,'adStd')]//a[contains(@class,'domainLink') or contains(@class,'test_domainLink')]/span");b(c)&&Utils.execTopBtmSponsQuery(".//*[@id='midRail']/div/div[contains(@class,'spl_shd') or contains(@class,'spl_unshd')]/div[contains(@class,'spl_ad')]/a[@class='nu']/span[@class='L4' or @class='newAdFont']",
".//*[@id='rpane']/div[contains(@class,'spl_shd') or contains(@class,'spl_unshd')]/div[contains(@class,'spl_ad')]/a[@class='nu']/span[@class='T10']");b(a)&&Utils.execRightSponsQuery(".//*[@id='sponsoredRight']//div[contains(@class,'spl_shd') or contains(@class,'spl_unshd')]/div[contains(@class,'spl_ad')]/a[@class='nu']/span[@class='L4' or @class='newAdFont']",".//*[@id='sponsoredRight']//div[contains(@class,'spl_shd') or contains(@class,'spl_unshd')]/div[contains(@class,'spl_ad')]/a[@class='nu']/span[@class='T10']");
b(e)&&Utils.execRightSponsQuery(".//*[@id='rr_sa']/div/div[contains(@class,'spl_shd') or contains(@class,'spl_unshd')]/div[contains(@class,'spl_ad')]/a[@class='nu']/span[@class='L4' or @class='newAdFont']",".//*[@id='rr_sa']/div/div[contains(@class,'spl_shd') or contains(@class,'spl_unshd')]/div[contains(@class,'spl_ad')]/a[@class='nu']/span[@class='T10']")}a=Utils.getSearchText();for(e=0;e<a.length;e++)c=Utils.getFormatLink(unescape(a[e])),Shasta.addURL(encodeURI(c))}return!0};c.createAnnotation=
function(){var a=navigator.userAgent.indexOf("Firefox"),c=function(b,c){if(!0!==Utils.isAlreadyAnnotated(b)){var d=document.createElement("a");d.onclick=function(){return!1};-1!==a?c.style.zIndex="0":d.style.position="relative";d.style.marginLeft="3px";d.appendChild(c);b.appendChild(d)}};if(b(Utils)){var e=[];e=Utils.getSearchNodes();for(var d=0;d<e.length;d++){var h=Utils.createImage(d);h&&c(e[d],h)}}return!0}}};c.initialize();return c}(a.SymBfw)})(executionContext);
