var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var h=a[d];h in b||(b[h]={});b=b[h]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,b){var d=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===b&&(b=d.length);b=Math.max(0,Math.min(b|0,d.length));for(var c=a.length;0<c&&0<b;)if(d[--b]!=a[--c])return!1;return 0>=c}},"es6","es3");
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,b){var d=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var c=d.length,k=a.length;b=Math.max(0,Math.min(b|0,d.length));for(var f=0;f<k&&b<c;)if(d[b++]!=a[f++])return!1;return f>=k}},"es6","es3");
(function(a){a.NSSS.sb_bing=function(){var a={},b;a.initialize=function(){a.parsePage=function(){var a=new URI(window.location.href);if(Utils){a.hostname().endsWith("livesearch.msn.co.kr")?(Utils.execSearchQuery("//div[@class='iePngFix']//li/dl/dt/a[(@class='a_blue') and (not(child::img))]"),Utils.execRightSponsQuery("//div[@id='news_side']//*[@id='news_side_list']/li/dl//dt/a[(@class='a_blue') and (not(child::img))]"),Utils.execTopBtmSponsQuery("//*[@id='overture_list']/li/dl/dt[@class='txt_inline']/a[@class='a_blue']",
"//*[@id='overture_list']/li/dl/dd[@class='txt_inline']"),gbKoreaSrchPage=!0):a.hostname().endsWith("bing.search.daum.net")?(Utils.execSearchQuery("//div[contains(@class,'collTot')]//li//span[@class='tit']/a[1][not(@class)]"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//li//span[@class='fl']/a[1]"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//table//td[contains(@class,'l_') or @class='txt']/a[1]"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//dd[contains(@id,'vclip_DD')]//span[@class='tit']/a[1]"),
Utils.execSearchQuery("//div[contains(@class,'collTot')]//dd[@class='c_desc']//li[@class='t']/a[1]"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//li//span[@class='tit']/a[contains(@class,'fL')]"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//li//div[contains(@class,'dicObj')]/a[1]"),Utils.execTopBtmSponsQuery("//div[contains(@class,'collTotAd')]//ul/li/a[1]","//div[contains(@class,'collTotAd')]//ul/li/span[@class='url']/a"),Utils.execSearchQuery("//div[contains(@class,'collTot')]//span/a[not(child::img) and (@class='newsTit fL')]"),
Utils.execSearchQuery("//div[contains(@class,'collTot')]//li[not(@class)]//p[not(child::span)]/a[not(child::img)] ")):a.hostname().startsWith("www.bing.com")&&a.path().startsWith("/news/search")?(Utils.execSearchQuery("//div[contains(@class,'sn_r')]//div[contains(@class,'newstitle')]/a"),Utils.execSearchQuery("//div[contains(@class,'TextContainer entry-content')]/ul/li/a[not(child::img)]")):(Utils.execSearchQuery("//div[@id='results']//li//div[contains(@class,'lst')]//h3/a[not(child::img)]"),Utils.execSearchQuery("//ol[@id='b_results']//li[contains(@class,'b_algo') or contains(@class,'b_ans')]//h2//a[not(child::img)]"),
Utils.execSearchQuery("//*[@id='b_results']//li[contains(@class,'b_algo') or contains(@class,'b_ans') or contains(@class,'b_ad')]//*[contains(@class, 'b_deep')]//h3/a[not(child::img)]"),Utils.execRightSponsQuery("//div[starts-with(@class,'sb_adsN')]//li/div/h3/a|//div[starts-with(@class,'sb_adsN')]//li/a/h3","//div[starts-with(@class,'sb_adsN')]//li//cite"),Utils.execTopBtmSponsQuery("//div[contains(@class,'sb_adTA')]//h2/a","//div[contains(@class,'sb_adTA')]//div//cite"),Utils.execSearchQuery("//li[starts-with(@class,'b_ans')]//div[starts-with(@class,'b_rich')]//div[starts-with(@class,'mcd')]//h4/a[1]"),
Utils.execSearchQuery("//li[starts-with(@class,'b_ans')]//div[starts-with(@class,'b_rich')]//li//h5/a[1]"),Utils.execSearchQuery("//div[@class='sr_dcard' or @class='ec']//h3/a[not(child::img)]"),Utils.execSearchQuery("//div[starts-with(@class,'ans')]//h2[not(descendant::span)]/div/a[not(child::img)]"),Utils.execSearchQuery("//li[starts-with(@class, 'sb_ans')]//div[starts-with(@class,'ans')]//h2[not(descendant::span)]/a[not(child::img)]"),Utils.execSearchQuery("//div[starts-with(@class,'ans')]//h2[descendant::span]/div/a[not(child::img)]",
"align"),Utils.execSearchQuery("//div[(@class='vsa')or (@class='ans')]//h2/a[not(@class) and not(child::img)]"),Utils.execSearchQuery("//div[@id='sa_bop']//div[@class='ans3']//li[not(parent::div)]/a[not(child::img)]"),Utils.execSearchQuery("//div[starts-with(@class,'ans')or (@id='sa_bop')]//div[@class='sn_rct']//li//span/a[1]"),Utils.execTopBtmSponsQuery("//div[@id='results_container']/div[@class='sx_m']/h3[@class='sx_t']/span[@class='sx_b']/a","//div[@id='results_container']/div[@class='sx_m']/div[@class='sx_su']/cite"));
a=Utils.getSearchText();0<a.length&&(b=Shasta.getPageDirection().toLowerCase());for(var c=0;c<a.length;c++){var k=Utils.getFormatLink(unescape(a[c]));Shasta.addURL(encodeURI(k))}}return!0};a.createAnnotation=function(){var a=navigator.userAgent.indexOf("Firefox"),c=Utils.getSearchFlags(),k=function(){return!1},f=function(d,f,g){var m=d.parentNode,n=d.nextSibling,h=!1;if(!0!==Utils.isAlreadyAnnotated(m)){n&&!0!==(3===n.nodeType&&!/\S/.test(n.nodeValue))||(h=!0);var e=document.createElement("a");e.style.textDecoration=
"none";e.style.cursor="pointer";e.style.padding="0px";f.style.top="0px";e.style.display="inline";e.onclick=k;e.appendChild(f);d.style.display="inline";var l=!0;-1===a&&(l=!1,f.style.position="static",c[g].toLowerCase()===Utils.constants.NORMAL?(d.appendChild(document.createTextNode(" ")),d.appendChild(e)):"ltr"===b&&(e.style.position="relative"));if(c[g].toLowerCase()!==Utils.constants.NORMAL||!0===l)h?(m.appendChild(document.createTextNode(" ")),m.appendChild(e)):(m.insertBefore(document.createTextNode(" "),
n),m.insertBefore(e,n))}},l=[];Shasta.getPageDirection();l=Utils.getSearchNodes();for(var g=0;g<l.length;g++){var p=void 0;p=Utils.createImage(g);f(l[g],p,g)}return!0}};a.initialize();return a}()})(executionContext);
