var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};
$jscomp.checkStringArgs=function(a,d,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,b,n){if(d){b=$jscomp.global;a=a.split(".");for(n=0;n<a.length-1;n++){var m=a[n];m in b||(b[m]={});b=b[m]}a=a[a.length-1];n=b[a];d=d(n);d!=n&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,b){var d=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var m=d.length,e=a.length;b=Math.max(0,Math.min(b|0,d.length));for(var q=0;q<e&&b<m;)if(d[b++]!=a[q++])return!1;return q>=e}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var d=this;d instanceof String&&(d=String(d));var m=d.length;b=b||0;for(0>b&&(b=Math.max(b+m,0));b<m;b++){var e=d[b];if(e===a||Object.is(e,a))return!0}return!1}},"es7","es3");$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
(function(a){a.NSSS.sb_yahoo=function(a,b){var d=b.utils.isntNil,m=b.utils.isNil,e=a.constants,q=b.extensionAdapter,w=b.utils,t=a.uiConstants.MESSAGES,y=a.NSSSHelper,g={},x=!1,z=!1,A=!1,B=!1,u=[],v=[];g.initialize=function(){if(d(Shasta)){var a=function(a){a=a?a:window.event;window.event?a.cancelBubble=!0:a.stopPropagation()};g.parsePage=function(){var a=function(){var a=!0;"hk.search.yahoo.com"===window.location.hostname.toLowerCase()?(Utils.execSearchQuery("//div[contains(@class,'algo-sr')]//h3//a[contains(@class,'ac-algo')]"),
Utils.execSearchQuery("//div[contains(@id,'web') or contains(@id,'kp') or contains(@id,'ysch')]//li/div//a[contains(@class,'ttl')]"),Utils.execSearchQuery("//div[starts-with(@class,'compTitle')]/h3[@class='title']/a"),Utils.execSearchQuery("//div[contains(@class,'sc-knowledge')]//li/a[not(child::img)][1]"),Utils.execTopBtmSponsQuery("//div[contains(@class,'ads')]//h3//a[contains(@class,'ov-h')]","//div[contains(@class,'ads')]//h3//a[contains(@class,'ov-h')]"),Utils.execTopBtmSponsQuery("//div[contains(@class,'spns') or contains(@class,'ads horiz')]//li/div[not(contains(@class, 'abs'))]/a[not(contains(@class, 'nradan'))][1]",
"//div[contains(@class,'spns') or contains(@class,'ads horiz')]//li/em[1]"),Utils.execRightSponsQuery("//div[@id='east' or contains(@id,'sec')]//ul/li[not(@class)]/a[not(child::img)]","//div[@id='east' or contains(@id,'sec')]//li[not (@class='yschprom')]//em[(not(@class))][1]"),Utils.execSearchQuery("//div[@id='yschiy']/cite/a[not(child::img)]"),Utils.execSearchQuery("//div[@class='res sc']//div/a[contains(@class,'spt')]"),Utils.execRightSponsQuery("//div[@id='east']/ul[starts-with(@class,'ead')]//li/a",
"//div[@id='east']/ul[starts-with(@class,'ead')]//li/em"),a=!1,x=!0):"hk.m.search.yahoo.com"===window.location.hostname.toLowerCase()?(Utils.execSearchQuery("//div[contains(@id,'web') or contains(@id,'kp')]//li/div//a[contains(@class,'ttl')]"),Utils.execSearchQuery("//div[starts-with(@class,'compTitle')]/h3[@class='title']/a"),Utils.execSearchQuery("//div[contains(@class,'sc-knowledge')]//li/a[not(child::img)][1]"),Utils.execTopBtmSponsQuery("//div[contains(@class,'spns') or contains(@class,'ads horiz')]//li/div/a[not(child::img)][1]",
"//div[contains(@class,'spns') or contains(@class,'ads horiz')]//li/em[1]"),Utils.execRightSponsQuery("//div[@id='east' or contains(@id,'sec')]//ul/li[not(@class)]/a[not(child::img)]","//div[@id='east' or contains(@id,'sec')]//li[not (@class='yschprom')]//em[(not(@class))][1]"),Utils.execSearchQuery("//div[@id='yschiy']/cite/a[not(child::img)]"),Utils.execSearchQuery("//div[@class='res sc']//div/a[contains(@class,'spt')]"),Utils.execRightSponsQuery("//div[@id='east']/ul[starts-with(@class,'ead')]//li/a",
"//div[@id='east']/ul[starts-with(@class,'ead')]//li/em"),a=!1,x=!0):"kr.search.yahoo.com"===window.location.hostname.toLowerCase()?(Utils.execSearchQuery("//div[@id='web']//li//div/h3/a[not(child::img)]"),Utils.execSearchQuery("//div[starts-with(@id,'bl') or @id='vdo']//li/div[@class='cn']/h4/a[not(child::img)]"),Utils.execSearchQuery("//div[@id='ks2']//div[@class='box']/p/a[not(child::img)]"),Utils.execSearchQuery("//div[@id='vpr']//div/strong//a[not(child::img)]"),Utils.execSearchQuery("//div[@id='nws']//div[@class='box']//div[@class='rt']/p/a[not(child::img)]"),
Utils.execSearchQuery("//div[@id='gg1']//div[@class='box']/span/p/a[not(child::img)]"),Utils.execSearchQuery("//div[@id='go']//dd/strong//a[not(child::img)and not(parent::span)]"),Utils.execSearchQuery("//div[@id='dic']//dd/span/a[1][not(child::img)]"),Utils.execSearchQuery("//div[(@id='poi')]//div/h5//a[contains(@class,'spt')]"),Utils.execSearchQuery("//div[@id='sp1']//dd//a[(parent::h3) or ((parent::dd) and not(child::img))]"),Utils.execSearchQuery("//div[@class='yiy']/h4[(preceding-sibling::span)]/a[1]"),
Utils.execTopBtmSponsQuery("//div[contains(@class,'special-link')]//li//h3/a[not(child::img) and not(@class)]","//div[contains(@class,'special-link')]//li/em[1]"),Utils.execTopBtmSponsQuery("//div[contains(@class,'premium-link')]//li//h3/a[not(child::img) and not(@class)]","//div[contains(@class,'premium-link')]//li/div/a[not(child::img) and not(@class)]"),Utils.execTopBtmSponsQuery("//div[starts-with(@class,'ads horiz ')]//ul[@class='spns']//div[not(@class)]/a[not(child::img)]","//div[starts-with(@class,'ads horiz ')]//ul[@class='spns']//em/a[not(@class) and not(child::img)]"),
z=!0):"search.yahoo.co.jp"===window.location.hostname.toLowerCase()?(Utils.execSearchQuery("//div[@id='mIn']//div[@class='hd']//h3/a"),Utils.execSearchQuery("//div[@id='mIn']//div[@class='bd']//div[@class='row']//ul/li//a[not(child::img)]"),Utils.execTopBtmSponsQuery("//div[@id='mIn']//div[@class='bd']//ul/li//a[@class='t' and not(child::img)]","//div[@id='mIn']//div[@class='bd']//ul/li//span[@class='u']"),Utils.execTopBtmSponsQuery("//div[@id='mIn']//div[@class='bd']//h3/a","//div[@id='mIn']//div[@class='bd']//div[contains(@class,'cf') and not(contains(@class,'st1'))]/span[1]"),
Utils.execRightSponsQuery("//div[@id='sIn']//div[@class='bd']//a[not(child::img)]","//div[@id='sIn']//div[@class='bd']//span[@class='u']"),A=!0):"search.cn.yahoo.com"===window.location.hostname.toLowerCase()||"one.cn.yahoo.com"===window.location.hostname.toLowerCase()?(Utils.execSearchQuery("//div[@class='rst' or @class='yst-web']//h3/a[not(child::img)]"),Utils.execTopBtmSponsQuery("//div[contains(@class,'p4p') or contains(@id,'p4p')]//h3/em[1]","//div[contains(@class,'p4p') or contains(@id,'p4p')]//h3/em[1]"),
Utils.execRightSponsQuery("//div[@class='pr']//a[@class='pa']//em","//div[@class='pr']//a[@class='pa']//div[@class='f1']//div[@class='rel']")):window.location.href.startsWith("http://www.yahoo.cn/s?")||window.location.href.startsWith("https://www.yahoo.cn/s?")?(Utils.execSearchQuery("//div[@class='main_content']/div[@class='content']/ul[@class='results']/li[@class='record']/h3[@class='title']/a"),Utils.execSearchQuery("//div[@class='main_content']/div[@class='content']/ul[@class='results']/li[@class='record sc_news']/div/ul/li/a[@class='sub_title']"),
Utils.execSearchQuery("//div[@class='main_content']/div[@class='content']/ul[@class='results']/li[@class='record']/ul[@class='sitelink']/li/a")):"ca.search.yahoo.com"===window.location.hostname.toLowerCase()?(Utils.execSearchQuery("//div[contains(@class,'algo-sr')]//h3//a[contains(@class,'ac-algo')]"),Utils.execSearchQuery("//div[starts-with(@class,'compTitle')]/h3[@class='title']/a"),Utils.execTopBtmSponsQuery("//div[contains(@class,'spns') or contains(@class,'ads horiz')]//li/div/a[not(contains(@class,'pp-'))and not(child::img)]",
"//div[contains(@class,'spns') or contains(@class,'ads horiz')]//li//em[1]"),Utils.execRightSponsQuery("//div[@id='east']//li[not(@class)]/a[not(child::img)]","//div[@id='east']//li//em[1]"),Utils.execRightSponsQuery("//div[@id='east']/ul[starts-with(@class,'ead')]//li/a","//div[@id='east']/ul[starts-with(@class,'ead')]//li/em"),a=!1):"tw.search.yahoo.com"===window.location.hostname.toLowerCase()?(Utils.execSearchQuery("//div[contains(@id,'web')]//a[contains(@class,'ttl')]"),Utils.execSearchQuery("//div[starts-with(@class,'compTitle')]/h3[@class='title']/a"),
Utils.execTopBtmSponsQuery("//div[starts-with(@class,'adStd')]/div[not(@class)]/a","//div[starts-with(@class,'adStd')]/a[starts-with(@class,'test')]"),Utils.execSearchQuery("//div[contains(@class,'sc-knowledge') or contains(@class,'sc-shopping')]//li/a[not(child::img)]"),Utils.execSearchQuery("//div[@class='res sc']/div[contains(@class,'ttl')]/a[contains(@class,'spt')and not(child::img)]")):window.location.href.startsWith("http://search.yahoo.com/sponsored_search")||window.location.href.startsWith("https://search.yahoo.com/sponsored_search")?
Utils.execTopBtmSponsQuery("//div[@id='ad-srp']//li//h3/a[not(child::img)]","//div[@id='ad-srp']//li//div[(@class='res')]/span[(@class='url')]"):window.location.href.includes("search/dir")?(Utils.execSearchQuery("//div[contains(@id,'web')]//a[contains(@class,'ttl')]"),Utils.execTopBtmSponsQuery("//div[contains(@class,'spns') or contains(@class,'ads horiz')]//li/div[not(@class='abst')]/a[1 and not(@class) and not(child::img)]","//div[contains(@class,'spns') or contains(@class,'ads horiz')]//li//em[1 and not(parent::a)]")):
(Utils.execSearchQuery("//div[contains(@id,'web')]//h3//a[1]"),Utils.execSublinksSearchQuery("//div[contains(@id,'web')]//li[contains(@class, 'mb-12')]//a"),Utils.execTopBtmSponsQuery("//ul[contains(@class,'spns') or contains(@class,'ads horiz') or contains(@class,'eads')]/li/div[contains(@class,'ad-ttl') or contains(@class,'vert-ad-ttl')]/a[not(child::img)]","//ul[contains(@class,'spns') or contains(@class,'ads horiz') or contains(@class,'eads')]//li/em[1 and not(parent::a)]"));a&&(Utils.execRightSponsQuery("//div[contains(@class,'bcae') or contains(@class, 'bcaw')]//h3[@class='title']//a[1]",
"//div[contains(@class,'bcae') or contains(@class, 'bcaw')]//div[contains(@class,'compTitle')]//div//a[1]"),"in.search.yahoo.com"===window.location.hostname.toLowerCase()&&Utils.execRightSponsQuery("//div[@class='mod glue-spl']//li[not (@class='yschprom')]//a[(not(@class) and not(child::img))]","//div[@class='mod glue-spl']//li[not (@class='yschprom')]//em[1]"));Utils.execSearchQuery("//div[starts-with(@class,'res sc')]//tr/td[@class='news-r']//li/a[not(child::img)]");Utils.execSearchQuery("//ul[contains(@class,'compArticleList')]//li/h4//a[1]");
Utils.execSearchQuery("//div[@class='shpnr']//*[contains(@class,'ttl')]");Utils.execTopBtmSponsQuery("//div[contains(@class,'ads')]//div[@class='compTitle']//h3/a[1]","//div[contains(@class,'ads')]//div[@class='compTitle']//div[1]/a");Utils.execTopBtmSublinksQuery("//div[contains(@class,'bcas') or contains(@class, 'bcan')]//div[@class='layoutCenter']//div[contains(@class,'compList')]//a");Utils.execImageSponsQuery("//ul[contains(@class,'compImageList') and contains(@class, 'p-sta')]//li[contains(@class, 'm-0')]//a[contains(@class,'thmb')]");
Utils.execSearchQuery("//div[starts-with(@class,'res sc') and (following::div[contains(@id,'web')])]//a[contains(@class,'yschttl')]");Utils.execSearchQuery("//div[starts-with(@class,'res sc')]/h4/a[(not(@class) or (@class='spt')) and not(child::img)]");Utils.execSearchQuery("//div[contains(@class,'navset')]//div[contains(@class,'cnt')]//li[not(@class)]/a[not(child::img)]");Utils.execSearchQuery("//div[contains(@class,'sc-clues')]//a[contains(@class,'ttl')and not(child::img)]");Utils.execSearchQuery("//div[@id='main']//ol[@id='quickapp-prompt']//li//a[contains(@class,'ttl')and not(child::img)]");
Utils.execSearchQuery("//div[contains(@class,'tabview-content')]//li//div[contains(@class,'accrdn-panel')]//div[@class='wt-bd']/h3/a[not(child::img)]");Utils.execSearchQuery("//div[contains(@class,'tabview-content')]//li//div[contains(@class,'accrdn-panel')]//li/h3/a[not(child::img)]")},b=function(a,b){b=["/**","/*-"];var c;a=a.replace(/\u200B|\u2060/g,"");a=unescape(a);a=Utils.getFormatLink(a);for(var f=0;f<b.length&&-1==(c=a.lastIndexOf(b[f]));f++);c=-1!=c?a.slice(c+b[f].length):a;if(c.match(/rlid/)&&
c.match(/u=/)){if(b=c.indexOf("u="),a=c.indexOf("&rlid"),-1!=b&&-1!=a&&b<a){a=c.substring(b+2,a);b="";try{b=atob(a)}catch(D){q.sendMessage({name:t.CLICK_PREVENTION_FAILURE_TELEMETRY,message:{url:encodeURIComponent(c)}}),b=""}b=decodeURIComponent(b);c=new URI(b);a=URI.parseQuery(c._parts.query);c=a.MPRE;m(c)&&(c=a.ds_dest_url,m(c)&&(c=Utils.getFormatLink(b)))}}else c.match(/\.yahoo\.com/)&&c.match(/RU=/)&&(c=c.slice(c.lastIndexOf("RU=")+3),c=c.slice(0,c.indexOf("/RK=")));return encodeURI(c)};if(d(Utils)){a();
a=[];a=Utils.getSearchText();if(0>=a.length)return!1;u=Utils.getSearchNodes();for(var p=y.isYahooSERPPage(window.location.href),h=0;h<a.length;h++){var e=b(a[h],u[h]);(isAdvtLink=Utils.isAdvtLink(h))&&(e=g.replaceEncodedCharaters(e));p?Shasta.addURL(e,isAdvtLink):Shasta.addURL(e,null)}}return!0};g.replaceEncodedCharaters=function(a){if(!m(a)){for(var b=$jscomp.makeIterator([/%20%E2%80%BA%20/g]),f=b.next();!f.done;f=b.next())a=a.replace(f.value,"/");return a}};g.handleMessage=function(a,b,d){switch(a.name){case t.UNDO_CLICK_PREVENTION:v.forEach(function(b){b.domain.toLowerCase()==
a.undoDomain.toLowerCase()&&b[e.CLICK_PREVENTION_NODE_LIST].forEach(function(a){g.undoClickPrevention(a)})});break;case t.REDO_CLICK_PREVENTION:v.forEach(function(a){var b=w.createNewGuid(),f=Shasta.getURLObject(a.index);a[e.CLICK_PREVENTION_NODE_LIST].forEach(function(a){g.doClickPrevention(a,f,b)})})}};g.undoClickPrevention=function(a){m(a)||q.sendMessage({name:t.RETRIEVE_CLICK_PREVENTION_URL,message:{clickPreventionUrlID:a.dataset[e.CLICK_PREVENTION_GUID]}},function(b){d(b)&&d(b.url)&&(a.href=
b.url,a.parentNode.removeEventListener(e.events.CLICK,g.stopPropagation,!0),a.parentNode.removeEventListener(e.events.MOUSE_DOWN,g.stopPropagation,!0))})};g.stopPropagation=function(a){a.stopPropagation();return!1};g.doClickPrevention=function(a,b,p){var h=new URI(b.url),f=new URI(a.href);h={url:a.href,urlIdentifier:p,replacedUrl:h.toString()};var l=f.search(!0)[e.URL_IDENTIFIER];d(l)&&d(a.dataset[e.ACTUAL_HREF])&&(h.url=a.dataset[e.ACTUAL_HREF]);q.sendMessage({name:t.STORE_CLICK_PREVENTION_URL,message:h},
function(f){if(d(f)&&d(f.inClickPreventionMap)){var c=new URI(b.url);c=c.scheme()+"://"+c.hostname()+c.path()+"?"+e.URL_IDENTIFIER+"="+p;!1===f.inClickPreventionMap&&(m(l)&&(a.dataset[e.ACTUAL_HREF]=a.href),a.href=c,a.parentNode.addEventListener(e.events.CLICK,g.stopPropagation,!0),a.parentNode.addEventListener(e.events.MOUSE_DOWN,g.stopPropagation,!0));a.dataset[e.CLICK_PREVENTION_GUID]=p}})};g.performClickAttribution=function(){y.isYahooSERPPage(window.location.href)&&u.forEach(function(a,b){var p=
Shasta.getURLObject(b),h=a.href;if("sb_unsafeAnnotation.svg"===p.srcimage){var f=Utils.getSearchFlags()[b];if(!Utils.isNormalLink(b)&&!m(p.url)){var l=w.createNewGuid(),r={};r[e.CLICK_PREVENTION_NODE_LIST]=[];r.href=p.url;r.domain=(new URI(p.url)).domain();r.index=b;r[e.CLICK_PREVENTION_NODE_LIST].push(a);g.doClickPrevention(a,p,l);if(f===Utils.constants.TOP_BOTTOM_SUBLINKS||f===Utils.constants.RIGHT_IMAGE_LINKS)v.push(r);else{b=a.closest(".compTitle");var c=b.querySelector("div > a");r[e.CLICK_PREVENTION_NODE_LIST].push(c);
g.doClickPrevention(c,p,l);c=h.indexOf("u=");var n=h.indexOf("&rlid");-1!=c&&-1!=n&&c<n?(h=h.substring(c+2,n),h="div.compText a[href*="+h+"]"):h="div.compText a";b=b.nextElementSibling;c=[];"layoutCenter"===b.getAttribute("class")&&(c=b.querySelectorAll(h));c.forEach(function(a){r[e.CLICK_PREVENTION_NODE_LIST].push(a);g.doClickPrevention(a,p,l)},l);v.push(r);a=a.closest({right:"div[class*=bcae], div[class*=bcaw]",topbottom:"div[class*=bcas], div[class*=bcan]"}[f]);d(a)&&(a.style.cursor="")}}}})};
g.createAnnotation=function(){var b=function(b,c){var d=!1,e=b.parentNode,f=b.nextSibling,C=!1;if(!e)return!1;if(!0!==Utils.isAlreadyAnnotated(e)){c.style.cssFloat=c.style.styleFloat="none";c.style.display="inline";z&&"p"!=e.nodeName.toLowerCase()&&(c.style.top="0px");if(x&&g[l].toLowerCase()==Utils.constants.TOP_BOTTOM){var k=document.createElement("span");k.style.display="inline";b.style.display="inline";k.onclick=a;k.appendChild(c);c=document.createElement("br");k.appendChild(c);c=k}A&&540<e.clientWidth&&
(k=document.createElement("br"),e.appendChild(k));f||(C=!0);if(C)x&&g[l].toLowerCase()==Utils.constants.RIGHT&&(b.currentStyle?c.style.marginLeft=b.currentStyle.marginLeft:window.getComputedStyle&&(b=window.getComputedStyle(b,null))&&(c.style.marginLeft=b.getPropertyValue("margin-left"))),e.appendChild(document.createTextNode(" ")),k=document.createElement("span"),k.style.display="inline",k.onclick=a,g[l].toLowerCase()==Utils.constants.RIGHT_IMAGE_LINKS&&(c.style.display="none"),k.appendChild(c),
e.appendChild(k);else{g[l].toLowerCase()!=Utils.constants.NORMAL&&f&&"em"==f.nodeName.toLowerCase()&&(d=!0);g[l].toLowerCase()==Utils.constants.RIGHT_IMAGE_LINKS&&(c.style.display="none");if(d||g[l].toLowerCase()==Utils.constants.RIGHT)b.style.display="inline";e.insertBefore(document.createTextNode(" "),f);e.insertBefore(c,f);d&&(c=document.createElement("br"),e.insertBefore(c,f),B=!0,h[m++]=e)}return!0}},e=function(){var a=Utils.IsSAEnabled();if(a)for(var b=0;b<h.length;b++){for(var d=0,e=0,g=!1,
f=h[b].parentNode.getElementsByTagName("img"),k=0;k<f.length;k++)-1!=f[k].src.indexOf(Shasta.getResProtocol())&&(d=k),f[k].src.match(v)&&(e=k,q=!0);if(q)if(e<d)f[e].style.cssFloat=f[e].style.styleFloat="left",f[d].style.left="5px";else{for(d=f[e].parentNode.nextSibling;null!=d;){if("em"==d.nodeName.toLowerCase()){g=!0;break}d=d.nextSibling}if(g)for(g=h[b].childNodes.length,d=h[b].childNodes,e=0;e<g;e++){f=d[e];if("br"==f.nodeName.toLowerCase()||"em"==f.nodeName.toLowerCase())break;3!=f.nodeType&&
(f.style.cssFloat=f.style.styleFloat="left")}}}(q||!a&&++c>t)&&clearInterval(w)};if(d(Utils)){if(0>=u.length)return!1;var g=[],h=[],m=0;g=Utils.getSearchFlags();for(var l=0;l<u.length;l++){var n=Utils.createImage(l);if(!b(u[l],n))return!1}if(B){var c=0,q=!1;b=Utils.getSADetectInterval();var t=Utils.getSADetectCnt();Utils.ResetSAEnabled();var v=Utils.getSAProtocol(),w=setInterval(e,b)}}return!0}}};g.initialize();return g}(a.NSSS,a.SymBfw)})(executionContext);SymBfw.extensionAdapter.addMessageListener(NSSS.sb_yahoo.handleMessage);
