var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var e=0;return function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,b){a!=Array.prototype&&a!=Object.prototype&&(a[e]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,e){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(b){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(b||"")+"_"+e++,b)}var e=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,e){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var b=0,g={next:function(){if(b<a.length){var d=b++;return{value:e(d,a[d]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(a,e,b,g){if(e){b=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var d=a[g];d in b||(b[d]={});b=b[d]}a=a[a.length-1];g=b[a];e=e(g);e!=g&&null!=e&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
(function(a){(function(a,b){var e=a.utils.isNil,d=a.utils.isntNil,l=a.utils.isString,k=a.extensionAdapter,h=b.config,c={_updateAttribute:function(a){if(!e(a.data)&&!1!==l(a.data.origin)){var f=k.getExtensionURL("");a.data.origin==f&&(d(a.data.sessionInfo)?(f=a.data.sessionInfo,c.sessionInfo={urlCategory:f.urlCategory,ssl:f.sslStatus,address:f.address},b.helpers.set_tab_id(f.tabid),f.hasOwnProperty("urlCategory")&&h.dockConfig.urlCategory.onlineBanking===f.urlCategory&&f.hasOwnProperty("sslStatus")&&
h.dockConfig.sslStatus.secure===f.sslStatus?(c._loadText("banking_protection_enabled"),document.body.setAttribute("category","banking")):(c._loadText("isolation_mode_enabled"),document.body.setAttribute("category","general"))):c.sessionInfo=null,d(a.data.prompt)&&!0===a.data.prompt?(c.promptBankingProtection=!0,document.body.setAttribute("mode","signin"),c._loadText("banking_protection_disabled"),a=document.getElementById("fgdock_close"),d(a)&&(a.style.display="none")):c.promptBankingProtection=!1)}},
_sendMessage:function(a,b){k.sendMessage({type:"fg_message_proxy",id:h.uiMessageProxy.EVENT_ID,realId:a,data:b})},_loadText:function(a){b.helpers.get_localized_strings(a,function(a){for(var b=Object.keys(a),f=0;f<b.length;f++){var c=document.getElementById(b[f]);d(c)&&(c.textContent=a[b[f]])}})}};window.addEventListener("message",c._updateAttribute,!1);window.onload=function(){var a=document.getElementById("fgdock");d(a)&&(a.addEventListener("mouseenter",function(a){b.helpers.isTrustedEvent(a)&&c._sendMessage(h.dockMouseEvent.EVENT_ID,
{evt_type:h.dockMouseEvent.eventType.mouseEnter})}),a.addEventListener("mouseleave",function(a){b.helpers.isTrustedEvent(a)&&c._sendMessage(h.dockMouseEvent.EVENT_ID,{evt_type:h.dockMouseEvent.eventType.mouseLeave})}));a=document.getElementById("fgdock_close");d(a)&&(a.addEventListener("contextmenu",function(a){b.helpers.isTrustedEvent(a)&&a.preventDefault()}),a.addEventListener("click",function(a){b.helpers.isTrustedEvent(a)&&(d(c.sessionInfo)&&c.sessionInfo.urlCategory===h.dockConfig.urlCategory.onlineBanking&&
c.sessionInfo.ssl==h.dockConfig.sslStatus.secure&&d(c.sessionInfo.address)?(c.removed_by_user=!0,a=new URL(c.sessionInfo.address),b.telemetry.pingActionLabelOB(b.telemetry.ACTION_TYPE.DOCK_X_BUTTON_CLICKED,a.hostname),b.helpers.set_skip_session(!0),b.helpers.launch_url_with_callback(c.sessionInfo.address,function(a){},{new_tab:!1}),c.sessionInfo=null):!0===c.promptBankingProtection?c._sendMessage(h.dockMouseEvent.EVENT_ID,{evt_type:h.dockMouseEvent.eventType.click,id:"fgdock_close"}):top.window.close())}));
a=document.getElementById("fg_faq");d(a)&&a.addEventListener("click",function(a){b.helpers.isTrustedEvent(a)&&(b.telemetry.pingAction(b.telemetry.ACTION_TYPE.LEARN_MORE_CLICKED_DOCK),a=b.config.helpid,d(c.sessionInfo)?b.config.dockConfig.urlCategory.onlineBanking===c.sessionInfo.urlCategory&&(a=b.config.helpid_online_banking):"signin"===document.body.getAttribute("mode")&&(a=b.config.helpid_online_banking),b.helpers.open_site_redirector(b.config.ssdcat,a))});a=document.getElementById("fg_leavefeedback_text");
d(a)&&(a.addEventListener("contextmenu",function(a){b.helpers.isTrustedEvent(a)&&a.preventDefault()}),a.addEventListener("click",function(a){b.helpers.isTrustedEvent(a)&&(a=b.config.leave_feedback_link,d(c.sessionInfo)?b.config.dockConfig.urlCategory.onlineBanking===c.sessionInfo.urlCategory&&(a=b.config.leave_feedback_link_OB):"signin"===document.body.getAttribute("mode")&&(a=b.config.leave_feedback_link_OB),b.helpers._appendParamAndLaunchFeedbackUrl(a))}));a=document.getElementById("fgdock_signin");
d(a)&&a.addEventListener("click",function(a){b.helpers.isTrustedEvent(a)&&c._sendMessage(h.dockMouseEvent.EVENT_ID,{evt_type:h.dockMouseEvent.eventType.click,id:"fgdock_signin"})});c._loadText("dock");!0===c.promptBankingProtection?c._loadText("banking_protection_disabled"):c._loadText("banking_protection_enabled")}})(a.SymBfw,a.FG)})(this);
